# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=[%@if extension autotools %]lo[% @else %]$(OBJEXT)[%@end @if%]
# Module Dependencies:[%
@for each $(OBJEXTG) var=O %][%
@if helsum %][%
@else %][%
   @if generate_nlo_virt %][%
         @for elements topolopy.keep.virt %][%
	 @if enable_truncation_orders %][%
	 @for each 0 1 2 var=efto %]
abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%]: globals.[%O%]
d[%$_%]_[% efto %]h[%helicity%]l1.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%]
d[%$_%]_[% efto %]h[%helicity%]l1d.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%][%
         @end @for %][%
	 @else %]
abbrevd[%$_%]h[%helicity%].[%O%]: globals.[%O%]
d[%$_%]h[%helicity%]l1.[%O%]: abbrevd[%$_%]h[%helicity%].[%O%]
d[%$_%]h[%helicity%]l1d.[%O%]: abbrevd[%$_%]h[%helicity%].[%O%][%
	 @end @if %][%
         @end @for %][%
@if extension quadruple %][%
         @for elements topolopy.keep.virt %][%
	 @if enable_truncation_orders %][%
	 @for each 0 1 2 var=efto %]
abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%]: globals_qp.[%O%]
d[%$_%]_[% efto %]h[%helicity%]l1_qp.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%]
d[%$_%]_[% efto %]h[%helicity%]l1d_qp.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%][%
	 @end @for %][%
	 @else %]
abbrevd[%$_%]h[%helicity%]_qp.[%O%]: globals_qp.[%O%]
d[%$_%]h[%helicity%]l1_qp.[%O%]: abbrevd[%$_%]h[%helicity%]_qp.[%O%]
d[%$_%]h[%helicity%]l1d_qp.[%O%]: abbrevd[%$_%]h[%helicity%]_qp.[%O%][%
	 @end @if %][%
         @end @for %][%
   @end @if extension quadruple %][%

      	@if extension golem95 %][%
	@if enable_truncation_orders %][%
	@for each 0 1 2 var=efto %]
golem95_[% efto %]h[%helicity%].[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]_[% efto %]h[%helicity%]l1.[%O%] d[%$_%]_[% efto %]h[%helicity%]l1d.[%O%][%
         	@end @for %][%
	@end @for %][%
	@else %]
golem95h[%helicity%].[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]h[%helicity%]l1.[%O%] d[%$_%]h[%helicity%]l1d.[%O%][%
         	@end @for %][%
	@end @if %][%
	      @end @if extension golem95 %][%

      	@if extension ninja %][%
	@if enable_truncation_orders %][%
	@for each 0 1 2 var=efto %]
ninja_[% efto %]h[%helicity%].[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]_[% efto %]h[%helicity%]l1.[%O%] d[%$_%]_[% efto %]h[%helicity%]l131.[%O%] d[%$_%]_[% efto %]h[%helicity%]l132.[%O%] d[%$_%]_[% efto %]h[%helicity%]l121.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]_[% efto %]h[%helicity%]l131.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%]
d[%$_%]_[% efto %]h[%helicity%]l132.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%]
d[%$_%]_[% efto %]h[%helicity%]l121.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%][%
	@end @for %][%
	@end @for %][%
	@else %]
ninjah[%helicity%].[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]h[%helicity%]l1.[%O%] d[%$_%]h[%helicity%]l131.[%O%] d[%$_%]h[%helicity%]l132.[%O%] d[%$_%]h[%helicity%]l121.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]h[%helicity%]l131.[%O%]: abbrevd[%$_%]h[%helicity%].[%O%]
d[%$_%]h[%helicity%]l132.[%O%]: abbrevd[%$_%]h[%helicity%].[%O%]
d[%$_%]h[%helicity%]l121.[%O%]: abbrevd[%$_%]h[%helicity%].[%O%][%
	@end @for %][%
	@end @if %][%
        @if extension quadruple %][%
	@if enable_truncation_orders %][%
	@for each 0 1 2 var=efto %]
ninja_[% efto %]h[%helicity%]_qp.[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]_[% efto %]h[%helicity%]l1_qp.[%O%] d[%$_%]_[% efto %]h[%helicity%]l131_qp.[%O%] d[%$_%]_[% efto %]h[%helicity%]l132_qp.[%O%] d[%$_%]_[% efto %]h[%helicity%]l121_qp.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]_[% efto %]h[%helicity%]l131_qp.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%]
d[%$_%]_[% efto %]h[%helicity%]l132_qp.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%]
d[%$_%]_[% efto %]h[%helicity%]l121_qp.[%O%]: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%][%
	@end @for %][%
	@end @for %][%
	@else %]
ninjah[%helicity%]_qp.[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]h[%helicity%]l1_qp.[%O%] d[%$_%]h[%helicity%]l131_qp.[%O%] d[%$_%]h[%helicity%]l132_qp.[%O%] d[%$_%]h[%helicity%]l121_qp.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]h[%helicity%]l131_qp.[%O%]: abbrevd[%$_%]h[%helicity%]_qp.[%O%]
d[%$_%]h[%helicity%]l132_qp.[%O%]: abbrevd[%$_%]h[%helicity%]_qp.[%O%]
d[%$_%]h[%helicity%]l121_qp.[%O%]: abbrevd[%$_%]h[%helicity%]_qp.[%O%][%
	@end @for %][%
	@end @if %][%
        @end @if extension quadruple %][%
	@end @if extension ninja %][%
   @end @if generate_nlo_virt%][%
@end @if helsum %][%
	@if enable_truncation_orders %][%
@for each 0 1 2 var=efto %]
amplitudeh[%helicity%]_[% efto %].[%O%]: globals.[%O%][% @if generate_lo_diagrams %] diagramsl0_[% efto %].[%O%][% @end @if %][%
@if helsum %][%
@else %][%
	      @if extension golem95 %] golem95_[% efto %]h[%helicity%].[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninja_[% efto %]h[%helicity%].[%O%][%
                 @if extension quadruple %] ninja_[% efto %]h[%helicity%]_qp.[%O%][%
		 @end @if %][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0_[% efto %].[%O%][%
		   @if internal REQUIRE_FR5 %] diagramsl0_[% efto %]fr5.[%O%][%
			@end @if %][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%][%
            @end @for %][%
      @end @if %][%
@end @if helsum %][%
@end @for %][%
@else %]
amplitudeh[%helicity%].[%O%]: globals.[%O%][% @if generate_lo_diagrams %] diagramsl0.[%O%][% @end @if %][%
@if helsum %][%
@else %][%
	      @if extension golem95 %] golem95h[%helicity%].[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninjah[%helicity%].[%O%][%
                 @if extension quadruple %] ninjah[%helicity%]_qp.[%O%][%
		 @end @if %][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0.[%O%][%
		   @if internal REQUIRE_FR5 %] diagramsl0fr5.[%O%][%
			@end @if %][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%]h[%helicity%].[%O%][%
            @end @for %][%
      @end @if %][%
@end @if helsum %][%
@end @if %][%
@if extension quadruple %][%
@if enable_truncation_orders %][%
@for each 0 1 2 var=efto %]
amplitudeh[%helicity%]_[% efto %]_qp.[%O%]: globals_qp.[%O%][% @if generate_lo_diagrams %] diagramsl0_[% efto %]_qp.[%O%][% @end @if %][%
@if helsum %][%
@else %][%
	      @if extension golem95 %] golem95_[% efto %]h[%helicity%]_qp.[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninja_[% efto %]h[%helicity%]_qp.[%O%][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0_[% efto %]_qp.[%O%][%
		   @if internal REQUIRE_FR5 %] diagramsl0_[% efto %]fr5_qp.[%O%][%
			@end @if %][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%][%
            @end @for %][%
      @end @if %][%
@end @if helsum %][%
@end @for %][%
@else %]
amplitudeh[%helicity%]_qp.[%O%]: globals_qp.[%O%][% @if generate_lo_diagrams %] diagramsl0_qp.[%O%][% @end @if %][%
@if helsum %][%
@else %][%
	      @if extension golem95 %] golem95h[%helicity%]_qp.[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninjah[%helicity%]_qp.[%O%][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0_qp.[%O%][%
		   @if internal REQUIRE_FR5 %] diagramsl0fr5_qp.[%O%][%
			@end @if %][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%]h[%helicity%]_qp.[%O%][%
            @end @for %][%
      @end @if %][%
@end @if helsum %][%
@end @if %][%
@end @if %][%
@end @for %][%

@for each $(OBJEXTG) var=O %][%
   @if generate_lo_diagrams %][%
   @if enable_truncation_orders %][%
   @for each 0 1 2 var=efto %]   
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0_[% efto %].mod: diagramsl0_[% efto %].[%O%][%
   @for elements topolopy.keep.tree %]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l0.mod: d[%$_%]_[% efto %]h[%helicity%]l0.[%O%][%
   @end @for %][%
       @if internal REQUIRE_FR5 %]
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0_[% efto %]fr5.mod: diagramsl0_[% efto %]fr5.[%O%][%
	@end @if %][%
   @if extension quadruple %]
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0_[% efto %]_qp.mod: diagramsl0_[% efto %]_qp.[%O%][%
   @for elements topolopy.keep.tree %]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l0_[% efto %]_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l0_qp.[%O%][%
   @end @for %][%
   @end @if extension quadruple %][%
   @end @for %][%
   @else %]
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0.mod: diagramsl0.[%O%][%
   @for elements topolopy.keep.tree %]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l0.mod: d[%$_%]h[%helicity%]l0.[%O%][%
   @end @for %][%
       @if internal REQUIRE_FR5 %]
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0fr5.mod: diagramsl0fr5.[%O%][%
	@end @if %][%
   @if extension quadruple %]
[% process_name asprefix=\_ %]diagramsh[% helicity %]l0_qp.mod: diagramsl0_qp.[%O%][%
   @for elements topolopy.keep.tree %]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l0_qp.mod: d[%$_%]h[%helicity%]l0_qp.[%O%][%
   @end @for %][%
   @end @if extension quadruple %][%
   @end @if %][%
   @end @if generate_lo_diagrams %][%
@if helsum %][%
@else %][%

		@if extension golem95 %][%
		@if enable_truncation_orders %][%
		@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]golem95_[% efto %]h[%helicity%].mod: golem95_[% efto %]h[%helicity%].[%O%][%
   		@end @for %][%
		@else %]
[% process_name asprefix=\_ %]golem95h[%helicity%].mod: golem95h[%helicity%].[%O%][%
		@end @if %][%
		@end @if extension golem95 %][%

		@if extension ninja %][%
		@if enable_truncation_orders %][%
		@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]ninja_[% efto %]h[%helicity%].mod: ninja_[% efto %]h[%helicity%].[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l131.mod: d[%$_%]_[% efto %]h[%helicity%]l131.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l132.mod: d[%$_%]_[% efto %]h[%helicity%]l132.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l121.mod: d[%$_%]_[% efto %]h[%helicity%]l121.[%O%][%
			@end @for %][%
                @if extension quadruple %]
[% process_name asprefix=\_ %]ninja_[% efto %]h[%helicity%]_qp.mod: ninja_[% efto %]h[%helicity%]_qp.[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l131_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l131_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l132_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l132_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l121_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l121_qp.[%O%][%
			@end @for %][%
		@end @if extension quadruple %][%
		@end @for %][%
		@else %]
[% process_name asprefix=\_ %]ninjah[%helicity%].mod: ninjah[%helicity%].[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l131.mod: d[%$_%]h[%helicity%]l131.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l132.mod: d[%$_%]h[%helicity%]l132.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l121.mod: d[%$_%]h[%helicity%]l121.[%O%][%
			@end @for %][%
                @if extension quadruple %]
[% process_name asprefix=\_ %]ninjah[%helicity%]_qp.mod: ninjah[%helicity%]_qp.[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l131_qp.mod: d[%$_%]h[%helicity%]l131_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l132_qp.mod: d[%$_%]h[%helicity%]l132_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l121_qp.mod: d[%$_%]h[%helicity%]l121_qp.[%O%][%
			@end @for %][%
		@end @if extension quadruple %][%
		@end @if %][%
		@end @if extension ninja %][%
   @if generate_nlo_virt %][%
         @for elements topolopy.keep.virt %][%
	 @if enable_truncation_orders %][%
		@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]abbrevd[%$_%]_[% efto %]h[%helicity%].mod: abbrevd[%$_%]_[% efto %]h[%helicity%].[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l1.mod: d[%$_%]_[% efto %]h[%helicity%]l1.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l1d.mod: d[%$_%]_[% efto %]h[%helicity%]l1d.[%O%][%
		@end @for %][%
	 @else %]
[% process_name asprefix=\_ %]abbrevd[%$_%]h[%helicity%].mod: abbrevd[%$_%]h[%helicity%].[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l1.mod: d[%$_%]h[%helicity%]l1.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l1d.mod: d[%$_%]h[%helicity%]l1d.[%O%][%
	 @end @if %][%
         @end @for %][%
      @if extension quadruple %][%
         @for elements topolopy.keep.virt %][%
	 @if enable_truncation_orders %][%
		@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.mod: abbrevd[%$_%]_[% efto %]h[%helicity%]_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l1_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l1_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]_[% efto %]h[%helicity%]l1d_qp.mod: d[%$_%]_[% efto %]h[%helicity%]l1d_qp.[%O%][%
		@end @for %][%
	 @else %]
[% process_name asprefix=\_ %]abbrevd[%$_%]h[%helicity%]_qp.mod: abbrevd[%$_%]h[%helicity%]_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l1_qp.mod: d[%$_%]h[%helicity%]l1_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]h[%helicity%]l1d_qp.mod: d[%$_%]h[%helicity%]l1d_qp.[%O%][%
	 @end @if %][%
         @end @for %][%
   @end @if extension quadruple %][%
   @end @if generate_nlo_virt%][%
	@if enable_truncation_orders %][%
	@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]amplitudeh[% helicity %]_[% efto %].mod: amplitudeh[%helicity%]_[% efto %].[%O%][%
   	@end @for %][%
	@else %]
[% process_name asprefix=\_ %]amplitudeh[% helicity %].mod: amplitudeh[%helicity%].[%O%][%
   	@end @if %]
[% process_name asprefix=\_ %]globalsh[% helicity %].mod: globals.[%O%][%
@if extension quadruple %][%
	@if enable_truncation_orders %][%
	@for each 0 1 2 var=efto %]
[% process_name asprefix=\_ %]amplitudeh[% helicity %]_[% efto %]_qp.mod: amplitudeh[%helicity%]_[% efto %]_qp.[%O%][%
   	@end @for %][%
	@else %]
[% process_name asprefix=\_ %]amplitudeh[% helicity %]_qp.mod: amplitudeh[%helicity%]_qp.[%O%][%
   	@end @if %]
[% process_name asprefix=\_ %]globalsh[% helicity %]_qp.mod: globals_qp.[%O%][%
@end @if %][%
@end @if helsum %][%
@end @for %]
