# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=[%@if extension autotools %]lo[% @else %]$(OBJEXT)[%@end @if%]
# Module Dependencies:[%
@for each $(OBJEXTG) var=O %][%
   @if generate_nlo_virt %][%
         @for elements topolopy.keep.virt %]
abbrevd[%$_%].[%O%]: globals.[%O%]
d[%$_%]l1.[%O%]: abbrevd[%$_%].[%O%][% 
            	@if internal GENERATE_DERIVATIVES %]
d[%$_%]l1d.[%O%]: abbrevd[%$_%].[%O%][%
	           @end @if %][%
         @end @for %][%
@if extension quadruple %][%
         @for elements topolopy.keep.virt %]
abbrevd[%$_%]_qp.[%O%]: globals_qp.[%O%]
d[%$_%]l1_qp.[%O%]: abbrevd[%$_%]_qp.[%O%][%
            	@if internal GENERATE_DERIVATIVES %]
d[%$_%]l1d_qp.[%O%]: abbrevd[%$_%]_qp.[%O%][%
	           @end @if %][%
         @end @for %][%
   @end @if extension quadruple %][%

      	@if extension golem95 %]
golem95.[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]l1.[%O%][%
					@if internal GENERATE_DERIVATIVES
						%] d[%$_%]l1d.[%O%][%
					@end @if %][%
         	@end @for %][%
	      @end @if extension golem95 %][%

      	@if extension ninja %]
ninja.[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]l1.[%O%] d[%$_%]l131.[%O%] d[%$_%]l132.[%O%] d[%$_%]l121.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]l131.[%O%]: abbrevd[%$_%].[%O%]
d[%$_%]l132.[%O%]: abbrevd[%$_%].[%O%]
d[%$_%]l121.[%O%]: abbrevd[%$_%].[%O%][%
	@end @for %][%
        @if extension quadruple %]
ninja_qp.[%O%]: [%
         	@for elements topolopy.keep.virt %] \
	d[%$_%]l1_qp.[%O%] d[%$_%]l131_qp.[%O%] d[%$_%]l132_qp.[%O%] d[%$_%]l121_qp.[%O%][%
		@end @for %][%
@for elements topolopy.keep.virt %]
d[%$_%]l131_qp.[%O%]: abbrevd[%$_%]_qp.[%O%]
d[%$_%]l132_qp.[%O%]: abbrevd[%$_%]_qp.[%O%]
d[%$_%]l121_qp.[%O%]: abbrevd[%$_%]_qp.[%O%][%
	@end @for %][%
        @end @if extension quadruple %][%
	@end @if extension ninja %][%
   @end @if generate_nlo_virt%]
amplitude.[%O%]: globals.[%O%][%
	      @if extension golem95 %] golem95.[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninja.[%O%][%
                 @if extension quadruple %] ninja_qp.[%O%][%
		 @end @if %][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0.[%O%][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%].[%O%][%
            @end @for %][%
      @end @if %][%
@if extension quadruple %]
amplitude_qp.[%O%]: globals_qp.[%O%][% @if generate_lo_diagrams %] diagramsl0_qp.[%O%][% @end @if %][%
	      @if extension golem95 %] golem95_qp.[%O%][%
   	   @end @if %][%
	      @if extension ninja %] ninja_qp.[%O%][%
   	   @end @if %][%
	   @if generate_lo_diagrams %] \
			diagramsl0_qp.[%O%][%
		@end @if %][%
		@if generate_nlo_virt %][%
            @for elements topolopy.keep.virt %] \
			abbrevd[%$_%]_qp.[%O%][%
            @end @for %][%
      @end @if %][%
@end @if %][%
@end @for %][%

@for each $(OBJEXTG) var=O %][%
   @if generate_lo_diagrams %]
[% process_name asprefix=\_ %]diagramsl0.mod: diagramsl0.[%O%][%
   @for elements topolopy.keep.tree %]
[% process_name asprefix=\_ %]d[%$_%]l0.mod: d[%$_%]l0.[%O%][%
   @end @for %][%
   @end @if generate_lo_diagrams %][%

		@if extension golem95 %]
[% process_name asprefix=\_ %]golem95.mod: golem95.[%O%][%
			@end @if extension golem95 %][%

		@if extension ninja %]
[% process_name asprefix=\_ %]ninja.mod: ninja.[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]l131.mod: d[%$_%]l131.[%O%]
[% process_name asprefix=\_ %]d[%$_%]l132.mod: d[%$_%]l132.[%O%]
[% process_name asprefix=\_ %]d[%$_%]l121.mod: d[%$_%]l121.[%O%][%
			@end @for %][%
                @if extension quadruple %]
[% process_name asprefix=\_ %]ninja_qp.mod: ninja_qp.[%O%] [%
			@for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]d[%$_%]l131_qp.mod: d[%$_%]l131_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]l132_qp.mod: d[%$_%]l132_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]l121_qp.mod: d[%$_%]l121_qp.[%O%][%
			@end @for %][%
		@end @if extension quadruple %][%
		@end @if extension ninja %][%
   @if generate_nlo_virt %][%
         @for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]abbrevd[%$_%].mod: abbrevd[%$_%].[%O%]
[% process_name asprefix=\_ %]d[%$_%]l1.mod: d[%$_%]l1.[%O%][% 
            	@if internal GENERATE_DERIVATIVES %]
[% process_name asprefix=\_ %]d[%$_%]l1d.mod: d[%$_%]l1d.[%O%][%
	           @end @if %][%
         @end @for %][%
      @if extension quadruple %][%
         @for elements topolopy.keep.virt %]
[% process_name asprefix=\_ %]abbrevd[%$_%]_qp.mod: abbrevd[%$_%]_qp.[%O%]
[% process_name asprefix=\_ %]d[%$_%]l1_qp.mod: d[%$_%]l1_qp.[%O%][%
            	@if internal GENERATE_DERIVATIVES %]
[% process_name asprefix=\_ %]d[%$_%]l1d_qp.mod: d[%$_%]l1d_qp.[%O%][%
	           @end @if %][%
         @end @for %][%
   @end @if extension quadruple %][%
   @end @if generate_nlo_virt%]
[% process_name asprefix=\_ %]amplitude.mod: amplitude.[%O%]
[% process_name asprefix=\_ %]globals.mod: globals.[%O%][%
@if extension quadruple %]
[% process_name asprefix=\_ %]amplitude_qp.mod: amplitude_qp.[%O%]
[% process_name asprefix=\_ %]globals_qp.mod: globals_qp.[%O%][%
@end @if %][%
@end @for %]
