# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
abbrevd1_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d1_0h0l1.$(OBJEXTG): abbrevd1_0h0.$(OBJEXTG)
d1_0h0l1d.$(OBJEXTG): abbrevd1_0h0.$(OBJEXTG)
abbrevd1_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d1_1h0l1.$(OBJEXTG): abbrevd1_1h0.$(OBJEXTG)
d1_1h0l1d.$(OBJEXTG): abbrevd1_1h0.$(OBJEXTG)
abbrevd1_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d1_2h0l1.$(OBJEXTG): abbrevd1_2h0.$(OBJEXTG)
d1_2h0l1d.$(OBJEXTG): abbrevd1_2h0.$(OBJEXTG)
abbrevd2_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d2_0h0l1.$(OBJEXTG): abbrevd2_0h0.$(OBJEXTG)
d2_0h0l1d.$(OBJEXTG): abbrevd2_0h0.$(OBJEXTG)
abbrevd2_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d2_1h0l1.$(OBJEXTG): abbrevd2_1h0.$(OBJEXTG)
d2_1h0l1d.$(OBJEXTG): abbrevd2_1h0.$(OBJEXTG)
abbrevd2_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d2_2h0l1.$(OBJEXTG): abbrevd2_2h0.$(OBJEXTG)
d2_2h0l1d.$(OBJEXTG): abbrevd2_2h0.$(OBJEXTG)
abbrevd3_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d3_0h0l1.$(OBJEXTG): abbrevd3_0h0.$(OBJEXTG)
d3_0h0l1d.$(OBJEXTG): abbrevd3_0h0.$(OBJEXTG)
abbrevd3_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d3_1h0l1.$(OBJEXTG): abbrevd3_1h0.$(OBJEXTG)
d3_1h0l1d.$(OBJEXTG): abbrevd3_1h0.$(OBJEXTG)
abbrevd3_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d3_2h0l1.$(OBJEXTG): abbrevd3_2h0.$(OBJEXTG)
d3_2h0l1d.$(OBJEXTG): abbrevd3_2h0.$(OBJEXTG)
abbrevd4_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d4_0h0l1.$(OBJEXTG): abbrevd4_0h0.$(OBJEXTG)
d4_0h0l1d.$(OBJEXTG): abbrevd4_0h0.$(OBJEXTG)
abbrevd4_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d4_1h0l1.$(OBJEXTG): abbrevd4_1h0.$(OBJEXTG)
d4_1h0l1d.$(OBJEXTG): abbrevd4_1h0.$(OBJEXTG)
abbrevd4_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d4_2h0l1.$(OBJEXTG): abbrevd4_2h0.$(OBJEXTG)
d4_2h0l1d.$(OBJEXTG): abbrevd4_2h0.$(OBJEXTG)
abbrevd5_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d5_0h0l1.$(OBJEXTG): abbrevd5_0h0.$(OBJEXTG)
d5_0h0l1d.$(OBJEXTG): abbrevd5_0h0.$(OBJEXTG)
abbrevd5_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d5_1h0l1.$(OBJEXTG): abbrevd5_1h0.$(OBJEXTG)
d5_1h0l1d.$(OBJEXTG): abbrevd5_1h0.$(OBJEXTG)
abbrevd5_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d5_2h0l1.$(OBJEXTG): abbrevd5_2h0.$(OBJEXTG)
d5_2h0l1d.$(OBJEXTG): abbrevd5_2h0.$(OBJEXTG)
abbrevd7_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d7_0h0l1.$(OBJEXTG): abbrevd7_0h0.$(OBJEXTG)
d7_0h0l1d.$(OBJEXTG): abbrevd7_0h0.$(OBJEXTG)
abbrevd7_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d7_1h0l1.$(OBJEXTG): abbrevd7_1h0.$(OBJEXTG)
d7_1h0l1d.$(OBJEXTG): abbrevd7_1h0.$(OBJEXTG)
abbrevd7_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d7_2h0l1.$(OBJEXTG): abbrevd7_2h0.$(OBJEXTG)
d7_2h0l1d.$(OBJEXTG): abbrevd7_2h0.$(OBJEXTG)
abbrevd8_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d8_0h0l1.$(OBJEXTG): abbrevd8_0h0.$(OBJEXTG)
d8_0h0l1d.$(OBJEXTG): abbrevd8_0h0.$(OBJEXTG)
abbrevd8_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d8_1h0l1.$(OBJEXTG): abbrevd8_1h0.$(OBJEXTG)
d8_1h0l1d.$(OBJEXTG): abbrevd8_1h0.$(OBJEXTG)
abbrevd8_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d8_2h0l1.$(OBJEXTG): abbrevd8_2h0.$(OBJEXTG)
d8_2h0l1d.$(OBJEXTG): abbrevd8_2h0.$(OBJEXTG)
abbrevd10_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d10_0h0l1.$(OBJEXTG): abbrevd10_0h0.$(OBJEXTG)
d10_0h0l1d.$(OBJEXTG): abbrevd10_0h0.$(OBJEXTG)
abbrevd10_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d10_1h0l1.$(OBJEXTG): abbrevd10_1h0.$(OBJEXTG)
d10_1h0l1d.$(OBJEXTG): abbrevd10_1h0.$(OBJEXTG)
abbrevd10_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d10_2h0l1.$(OBJEXTG): abbrevd10_2h0.$(OBJEXTG)
d10_2h0l1d.$(OBJEXTG): abbrevd10_2h0.$(OBJEXTG)
abbrevd12_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d12_0h0l1.$(OBJEXTG): abbrevd12_0h0.$(OBJEXTG)
d12_0h0l1d.$(OBJEXTG): abbrevd12_0h0.$(OBJEXTG)
abbrevd12_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d12_1h0l1.$(OBJEXTG): abbrevd12_1h0.$(OBJEXTG)
d12_1h0l1d.$(OBJEXTG): abbrevd12_1h0.$(OBJEXTG)
abbrevd12_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d12_2h0l1.$(OBJEXTG): abbrevd12_2h0.$(OBJEXTG)
d12_2h0l1d.$(OBJEXTG): abbrevd12_2h0.$(OBJEXTG)
abbrevd14_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d14_0h0l1.$(OBJEXTG): abbrevd14_0h0.$(OBJEXTG)
d14_0h0l1d.$(OBJEXTG): abbrevd14_0h0.$(OBJEXTG)
abbrevd14_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d14_1h0l1.$(OBJEXTG): abbrevd14_1h0.$(OBJEXTG)
d14_1h0l1d.$(OBJEXTG): abbrevd14_1h0.$(OBJEXTG)
abbrevd14_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d14_2h0l1.$(OBJEXTG): abbrevd14_2h0.$(OBJEXTG)
d14_2h0l1d.$(OBJEXTG): abbrevd14_2h0.$(OBJEXTG)
abbrevd16_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d16_0h0l1.$(OBJEXTG): abbrevd16_0h0.$(OBJEXTG)
d16_0h0l1d.$(OBJEXTG): abbrevd16_0h0.$(OBJEXTG)
abbrevd16_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d16_1h0l1.$(OBJEXTG): abbrevd16_1h0.$(OBJEXTG)
d16_1h0l1d.$(OBJEXTG): abbrevd16_1h0.$(OBJEXTG)
abbrevd16_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d16_2h0l1.$(OBJEXTG): abbrevd16_2h0.$(OBJEXTG)
d16_2h0l1d.$(OBJEXTG): abbrevd16_2h0.$(OBJEXTG)
abbrevd18_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d18_0h0l1.$(OBJEXTG): abbrevd18_0h0.$(OBJEXTG)
d18_0h0l1d.$(OBJEXTG): abbrevd18_0h0.$(OBJEXTG)
abbrevd18_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d18_1h0l1.$(OBJEXTG): abbrevd18_1h0.$(OBJEXTG)
d18_1h0l1d.$(OBJEXTG): abbrevd18_1h0.$(OBJEXTG)
abbrevd18_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d18_2h0l1.$(OBJEXTG): abbrevd18_2h0.$(OBJEXTG)
d18_2h0l1d.$(OBJEXTG): abbrevd18_2h0.$(OBJEXTG)
abbrevd22_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d22_0h0l1.$(OBJEXTG): abbrevd22_0h0.$(OBJEXTG)
d22_0h0l1d.$(OBJEXTG): abbrevd22_0h0.$(OBJEXTG)
abbrevd22_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d22_1h0l1.$(OBJEXTG): abbrevd22_1h0.$(OBJEXTG)
d22_1h0l1d.$(OBJEXTG): abbrevd22_1h0.$(OBJEXTG)
abbrevd22_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d22_2h0l1.$(OBJEXTG): abbrevd22_2h0.$(OBJEXTG)
d22_2h0l1d.$(OBJEXTG): abbrevd22_2h0.$(OBJEXTG)
abbrevd23_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d23_0h0l1.$(OBJEXTG): abbrevd23_0h0.$(OBJEXTG)
d23_0h0l1d.$(OBJEXTG): abbrevd23_0h0.$(OBJEXTG)
abbrevd23_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d23_1h0l1.$(OBJEXTG): abbrevd23_1h0.$(OBJEXTG)
d23_1h0l1d.$(OBJEXTG): abbrevd23_1h0.$(OBJEXTG)
abbrevd23_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d23_2h0l1.$(OBJEXTG): abbrevd23_2h0.$(OBJEXTG)
d23_2h0l1d.$(OBJEXTG): abbrevd23_2h0.$(OBJEXTG)
abbrevd27_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d27_0h0l1.$(OBJEXTG): abbrevd27_0h0.$(OBJEXTG)
d27_0h0l1d.$(OBJEXTG): abbrevd27_0h0.$(OBJEXTG)
abbrevd27_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d27_1h0l1.$(OBJEXTG): abbrevd27_1h0.$(OBJEXTG)
d27_1h0l1d.$(OBJEXTG): abbrevd27_1h0.$(OBJEXTG)
abbrevd27_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d27_2h0l1.$(OBJEXTG): abbrevd27_2h0.$(OBJEXTG)
d27_2h0l1d.$(OBJEXTG): abbrevd27_2h0.$(OBJEXTG)
abbrevd29_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d29_0h0l1.$(OBJEXTG): abbrevd29_0h0.$(OBJEXTG)
d29_0h0l1d.$(OBJEXTG): abbrevd29_0h0.$(OBJEXTG)
abbrevd29_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d29_1h0l1.$(OBJEXTG): abbrevd29_1h0.$(OBJEXTG)
d29_1h0l1d.$(OBJEXTG): abbrevd29_1h0.$(OBJEXTG)
abbrevd29_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d29_2h0l1.$(OBJEXTG): abbrevd29_2h0.$(OBJEXTG)
d29_2h0l1d.$(OBJEXTG): abbrevd29_2h0.$(OBJEXTG)
abbrevd31_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d31_0h0l1.$(OBJEXTG): abbrevd31_0h0.$(OBJEXTG)
d31_0h0l1d.$(OBJEXTG): abbrevd31_0h0.$(OBJEXTG)
abbrevd31_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d31_1h0l1.$(OBJEXTG): abbrevd31_1h0.$(OBJEXTG)
d31_1h0l1d.$(OBJEXTG): abbrevd31_1h0.$(OBJEXTG)
abbrevd31_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d31_2h0l1.$(OBJEXTG): abbrevd31_2h0.$(OBJEXTG)
d31_2h0l1d.$(OBJEXTG): abbrevd31_2h0.$(OBJEXTG)
abbrevd33_0h0.$(OBJEXTG): globals.$(OBJEXTG)
d33_0h0l1.$(OBJEXTG): abbrevd33_0h0.$(OBJEXTG)
d33_0h0l1d.$(OBJEXTG): abbrevd33_0h0.$(OBJEXTG)
abbrevd33_1h0.$(OBJEXTG): globals.$(OBJEXTG)
d33_1h0l1.$(OBJEXTG): abbrevd33_1h0.$(OBJEXTG)
d33_1h0l1d.$(OBJEXTG): abbrevd33_1h0.$(OBJEXTG)
abbrevd33_2h0.$(OBJEXTG): globals.$(OBJEXTG)
d33_2h0l1.$(OBJEXTG): abbrevd33_2h0.$(OBJEXTG)
d33_2h0l1d.$(OBJEXTG): abbrevd33_2h0.$(OBJEXTG)
golem95_0h0.$(OBJEXTG):  \
	d1_0h0l1.$(OBJEXTG) d1_0h0l1d.$(OBJEXTG) \
	d2_0h0l1.$(OBJEXTG) d2_0h0l1d.$(OBJEXTG) \
	d3_0h0l1.$(OBJEXTG) d3_0h0l1d.$(OBJEXTG) \
	d4_0h0l1.$(OBJEXTG) d4_0h0l1d.$(OBJEXTG) \
	d5_0h0l1.$(OBJEXTG) d5_0h0l1d.$(OBJEXTG) \
	d7_0h0l1.$(OBJEXTG) d7_0h0l1d.$(OBJEXTG) \
	d8_0h0l1.$(OBJEXTG) d8_0h0l1d.$(OBJEXTG) \
	d10_0h0l1.$(OBJEXTG) d10_0h0l1d.$(OBJEXTG) \
	d12_0h0l1.$(OBJEXTG) d12_0h0l1d.$(OBJEXTG) \
	d14_0h0l1.$(OBJEXTG) d14_0h0l1d.$(OBJEXTG) \
	d16_0h0l1.$(OBJEXTG) d16_0h0l1d.$(OBJEXTG) \
	d18_0h0l1.$(OBJEXTG) d18_0h0l1d.$(OBJEXTG) \
	d22_0h0l1.$(OBJEXTG) d22_0h0l1d.$(OBJEXTG) \
	d23_0h0l1.$(OBJEXTG) d23_0h0l1d.$(OBJEXTG) \
	d27_0h0l1.$(OBJEXTG) d27_0h0l1d.$(OBJEXTG) \
	d29_0h0l1.$(OBJEXTG) d29_0h0l1d.$(OBJEXTG) \
	d31_0h0l1.$(OBJEXTG) d31_0h0l1d.$(OBJEXTG) \
	d33_0h0l1.$(OBJEXTG) d33_0h0l1d.$(OBJEXTG)
golem95_1h0.$(OBJEXTG):  \
	d1_1h0l1.$(OBJEXTG) d1_1h0l1d.$(OBJEXTG) \
	d2_1h0l1.$(OBJEXTG) d2_1h0l1d.$(OBJEXTG) \
	d3_1h0l1.$(OBJEXTG) d3_1h0l1d.$(OBJEXTG) \
	d4_1h0l1.$(OBJEXTG) d4_1h0l1d.$(OBJEXTG) \
	d5_1h0l1.$(OBJEXTG) d5_1h0l1d.$(OBJEXTG) \
	d7_1h0l1.$(OBJEXTG) d7_1h0l1d.$(OBJEXTG) \
	d8_1h0l1.$(OBJEXTG) d8_1h0l1d.$(OBJEXTG) \
	d10_1h0l1.$(OBJEXTG) d10_1h0l1d.$(OBJEXTG) \
	d12_1h0l1.$(OBJEXTG) d12_1h0l1d.$(OBJEXTG) \
	d14_1h0l1.$(OBJEXTG) d14_1h0l1d.$(OBJEXTG) \
	d16_1h0l1.$(OBJEXTG) d16_1h0l1d.$(OBJEXTG) \
	d18_1h0l1.$(OBJEXTG) d18_1h0l1d.$(OBJEXTG) \
	d22_1h0l1.$(OBJEXTG) d22_1h0l1d.$(OBJEXTG) \
	d23_1h0l1.$(OBJEXTG) d23_1h0l1d.$(OBJEXTG) \
	d27_1h0l1.$(OBJEXTG) d27_1h0l1d.$(OBJEXTG) \
	d29_1h0l1.$(OBJEXTG) d29_1h0l1d.$(OBJEXTG) \
	d31_1h0l1.$(OBJEXTG) d31_1h0l1d.$(OBJEXTG) \
	d33_1h0l1.$(OBJEXTG) d33_1h0l1d.$(OBJEXTG)
golem95_2h0.$(OBJEXTG):  \
	d1_2h0l1.$(OBJEXTG) d1_2h0l1d.$(OBJEXTG) \
	d2_2h0l1.$(OBJEXTG) d2_2h0l1d.$(OBJEXTG) \
	d3_2h0l1.$(OBJEXTG) d3_2h0l1d.$(OBJEXTG) \
	d4_2h0l1.$(OBJEXTG) d4_2h0l1d.$(OBJEXTG) \
	d5_2h0l1.$(OBJEXTG) d5_2h0l1d.$(OBJEXTG) \
	d7_2h0l1.$(OBJEXTG) d7_2h0l1d.$(OBJEXTG) \
	d8_2h0l1.$(OBJEXTG) d8_2h0l1d.$(OBJEXTG) \
	d10_2h0l1.$(OBJEXTG) d10_2h0l1d.$(OBJEXTG) \
	d12_2h0l1.$(OBJEXTG) d12_2h0l1d.$(OBJEXTG) \
	d14_2h0l1.$(OBJEXTG) d14_2h0l1d.$(OBJEXTG) \
	d16_2h0l1.$(OBJEXTG) d16_2h0l1d.$(OBJEXTG) \
	d18_2h0l1.$(OBJEXTG) d18_2h0l1d.$(OBJEXTG) \
	d22_2h0l1.$(OBJEXTG) d22_2h0l1d.$(OBJEXTG) \
	d23_2h0l1.$(OBJEXTG) d23_2h0l1d.$(OBJEXTG) \
	d27_2h0l1.$(OBJEXTG) d27_2h0l1d.$(OBJEXTG) \
	d29_2h0l1.$(OBJEXTG) d29_2h0l1d.$(OBJEXTG) \
	d31_2h0l1.$(OBJEXTG) d31_2h0l1d.$(OBJEXTG) \
	d33_2h0l1.$(OBJEXTG) d33_2h0l1d.$(OBJEXTG)
amplitudeh0_0.$(OBJEXTG): globals.$(OBJEXTG) golem95_0h0.$(OBJEXTG) \
			abbrevd1_0h0.$(OBJEXTG) \
			abbrevd2_0h0.$(OBJEXTG) \
			abbrevd3_0h0.$(OBJEXTG) \
			abbrevd4_0h0.$(OBJEXTG) \
			abbrevd5_0h0.$(OBJEXTG) \
			abbrevd7_0h0.$(OBJEXTG) \
			abbrevd8_0h0.$(OBJEXTG) \
			abbrevd10_0h0.$(OBJEXTG) \
			abbrevd12_0h0.$(OBJEXTG) \
			abbrevd14_0h0.$(OBJEXTG) \
			abbrevd16_0h0.$(OBJEXTG) \
			abbrevd18_0h0.$(OBJEXTG) \
			abbrevd22_0h0.$(OBJEXTG) \
			abbrevd23_0h0.$(OBJEXTG) \
			abbrevd27_0h0.$(OBJEXTG) \
			abbrevd29_0h0.$(OBJEXTG) \
			abbrevd31_0h0.$(OBJEXTG) \
			abbrevd33_0h0.$(OBJEXTG)
amplitudeh0_1.$(OBJEXTG): globals.$(OBJEXTG) golem95_1h0.$(OBJEXTG) \
			abbrevd1_1h0.$(OBJEXTG) \
			abbrevd2_1h0.$(OBJEXTG) \
			abbrevd3_1h0.$(OBJEXTG) \
			abbrevd4_1h0.$(OBJEXTG) \
			abbrevd5_1h0.$(OBJEXTG) \
			abbrevd7_1h0.$(OBJEXTG) \
			abbrevd8_1h0.$(OBJEXTG) \
			abbrevd10_1h0.$(OBJEXTG) \
			abbrevd12_1h0.$(OBJEXTG) \
			abbrevd14_1h0.$(OBJEXTG) \
			abbrevd16_1h0.$(OBJEXTG) \
			abbrevd18_1h0.$(OBJEXTG) \
			abbrevd22_1h0.$(OBJEXTG) \
			abbrevd23_1h0.$(OBJEXTG) \
			abbrevd27_1h0.$(OBJEXTG) \
			abbrevd29_1h0.$(OBJEXTG) \
			abbrevd31_1h0.$(OBJEXTG) \
			abbrevd33_1h0.$(OBJEXTG)
amplitudeh0_2.$(OBJEXTG): globals.$(OBJEXTG) golem95_2h0.$(OBJEXTG) \
			abbrevd1_2h0.$(OBJEXTG) \
			abbrevd2_2h0.$(OBJEXTG) \
			abbrevd3_2h0.$(OBJEXTG) \
			abbrevd4_2h0.$(OBJEXTG) \
			abbrevd5_2h0.$(OBJEXTG) \
			abbrevd7_2h0.$(OBJEXTG) \
			abbrevd8_2h0.$(OBJEXTG) \
			abbrevd10_2h0.$(OBJEXTG) \
			abbrevd12_2h0.$(OBJEXTG) \
			abbrevd14_2h0.$(OBJEXTG) \
			abbrevd16_2h0.$(OBJEXTG) \
			abbrevd18_2h0.$(OBJEXTG) \
			abbrevd22_2h0.$(OBJEXTG) \
			abbrevd23_2h0.$(OBJEXTG) \
			abbrevd27_2h0.$(OBJEXTG) \
			abbrevd29_2h0.$(OBJEXTG) \
			abbrevd31_2h0.$(OBJEXTG) \
			abbrevd33_2h0.$(OBJEXTG)
pc16_gghh_golem95_0h0.mod: golem95_0h0.$(OBJEXTG)
pc16_gghh_golem95_1h0.mod: golem95_1h0.$(OBJEXTG)
pc16_gghh_golem95_2h0.mod: golem95_2h0.$(OBJEXTG)
pc16_gghh_abbrevd1_0h0.mod: abbrevd1_0h0.$(OBJEXTG)
pc16_gghh_d1_0h0l1.mod: d1_0h0l1.$(OBJEXTG)
pc16_gghh_d1_0h0l1d.mod: d1_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd1_1h0.mod: abbrevd1_1h0.$(OBJEXTG)
pc16_gghh_d1_1h0l1.mod: d1_1h0l1.$(OBJEXTG)
pc16_gghh_d1_1h0l1d.mod: d1_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd1_2h0.mod: abbrevd1_2h0.$(OBJEXTG)
pc16_gghh_d1_2h0l1.mod: d1_2h0l1.$(OBJEXTG)
pc16_gghh_d1_2h0l1d.mod: d1_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd2_0h0.mod: abbrevd2_0h0.$(OBJEXTG)
pc16_gghh_d2_0h0l1.mod: d2_0h0l1.$(OBJEXTG)
pc16_gghh_d2_0h0l1d.mod: d2_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd2_1h0.mod: abbrevd2_1h0.$(OBJEXTG)
pc16_gghh_d2_1h0l1.mod: d2_1h0l1.$(OBJEXTG)
pc16_gghh_d2_1h0l1d.mod: d2_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd2_2h0.mod: abbrevd2_2h0.$(OBJEXTG)
pc16_gghh_d2_2h0l1.mod: d2_2h0l1.$(OBJEXTG)
pc16_gghh_d2_2h0l1d.mod: d2_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd3_0h0.mod: abbrevd3_0h0.$(OBJEXTG)
pc16_gghh_d3_0h0l1.mod: d3_0h0l1.$(OBJEXTG)
pc16_gghh_d3_0h0l1d.mod: d3_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd3_1h0.mod: abbrevd3_1h0.$(OBJEXTG)
pc16_gghh_d3_1h0l1.mod: d3_1h0l1.$(OBJEXTG)
pc16_gghh_d3_1h0l1d.mod: d3_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd3_2h0.mod: abbrevd3_2h0.$(OBJEXTG)
pc16_gghh_d3_2h0l1.mod: d3_2h0l1.$(OBJEXTG)
pc16_gghh_d3_2h0l1d.mod: d3_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd4_0h0.mod: abbrevd4_0h0.$(OBJEXTG)
pc16_gghh_d4_0h0l1.mod: d4_0h0l1.$(OBJEXTG)
pc16_gghh_d4_0h0l1d.mod: d4_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd4_1h0.mod: abbrevd4_1h0.$(OBJEXTG)
pc16_gghh_d4_1h0l1.mod: d4_1h0l1.$(OBJEXTG)
pc16_gghh_d4_1h0l1d.mod: d4_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd4_2h0.mod: abbrevd4_2h0.$(OBJEXTG)
pc16_gghh_d4_2h0l1.mod: d4_2h0l1.$(OBJEXTG)
pc16_gghh_d4_2h0l1d.mod: d4_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd5_0h0.mod: abbrevd5_0h0.$(OBJEXTG)
pc16_gghh_d5_0h0l1.mod: d5_0h0l1.$(OBJEXTG)
pc16_gghh_d5_0h0l1d.mod: d5_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd5_1h0.mod: abbrevd5_1h0.$(OBJEXTG)
pc16_gghh_d5_1h0l1.mod: d5_1h0l1.$(OBJEXTG)
pc16_gghh_d5_1h0l1d.mod: d5_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd5_2h0.mod: abbrevd5_2h0.$(OBJEXTG)
pc16_gghh_d5_2h0l1.mod: d5_2h0l1.$(OBJEXTG)
pc16_gghh_d5_2h0l1d.mod: d5_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd7_0h0.mod: abbrevd7_0h0.$(OBJEXTG)
pc16_gghh_d7_0h0l1.mod: d7_0h0l1.$(OBJEXTG)
pc16_gghh_d7_0h0l1d.mod: d7_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd7_1h0.mod: abbrevd7_1h0.$(OBJEXTG)
pc16_gghh_d7_1h0l1.mod: d7_1h0l1.$(OBJEXTG)
pc16_gghh_d7_1h0l1d.mod: d7_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd7_2h0.mod: abbrevd7_2h0.$(OBJEXTG)
pc16_gghh_d7_2h0l1.mod: d7_2h0l1.$(OBJEXTG)
pc16_gghh_d7_2h0l1d.mod: d7_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd8_0h0.mod: abbrevd8_0h0.$(OBJEXTG)
pc16_gghh_d8_0h0l1.mod: d8_0h0l1.$(OBJEXTG)
pc16_gghh_d8_0h0l1d.mod: d8_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd8_1h0.mod: abbrevd8_1h0.$(OBJEXTG)
pc16_gghh_d8_1h0l1.mod: d8_1h0l1.$(OBJEXTG)
pc16_gghh_d8_1h0l1d.mod: d8_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd8_2h0.mod: abbrevd8_2h0.$(OBJEXTG)
pc16_gghh_d8_2h0l1.mod: d8_2h0l1.$(OBJEXTG)
pc16_gghh_d8_2h0l1d.mod: d8_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd10_0h0.mod: abbrevd10_0h0.$(OBJEXTG)
pc16_gghh_d10_0h0l1.mod: d10_0h0l1.$(OBJEXTG)
pc16_gghh_d10_0h0l1d.mod: d10_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd10_1h0.mod: abbrevd10_1h0.$(OBJEXTG)
pc16_gghh_d10_1h0l1.mod: d10_1h0l1.$(OBJEXTG)
pc16_gghh_d10_1h0l1d.mod: d10_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd10_2h0.mod: abbrevd10_2h0.$(OBJEXTG)
pc16_gghh_d10_2h0l1.mod: d10_2h0l1.$(OBJEXTG)
pc16_gghh_d10_2h0l1d.mod: d10_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd12_0h0.mod: abbrevd12_0h0.$(OBJEXTG)
pc16_gghh_d12_0h0l1.mod: d12_0h0l1.$(OBJEXTG)
pc16_gghh_d12_0h0l1d.mod: d12_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd12_1h0.mod: abbrevd12_1h0.$(OBJEXTG)
pc16_gghh_d12_1h0l1.mod: d12_1h0l1.$(OBJEXTG)
pc16_gghh_d12_1h0l1d.mod: d12_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd12_2h0.mod: abbrevd12_2h0.$(OBJEXTG)
pc16_gghh_d12_2h0l1.mod: d12_2h0l1.$(OBJEXTG)
pc16_gghh_d12_2h0l1d.mod: d12_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd14_0h0.mod: abbrevd14_0h0.$(OBJEXTG)
pc16_gghh_d14_0h0l1.mod: d14_0h0l1.$(OBJEXTG)
pc16_gghh_d14_0h0l1d.mod: d14_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd14_1h0.mod: abbrevd14_1h0.$(OBJEXTG)
pc16_gghh_d14_1h0l1.mod: d14_1h0l1.$(OBJEXTG)
pc16_gghh_d14_1h0l1d.mod: d14_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd14_2h0.mod: abbrevd14_2h0.$(OBJEXTG)
pc16_gghh_d14_2h0l1.mod: d14_2h0l1.$(OBJEXTG)
pc16_gghh_d14_2h0l1d.mod: d14_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd16_0h0.mod: abbrevd16_0h0.$(OBJEXTG)
pc16_gghh_d16_0h0l1.mod: d16_0h0l1.$(OBJEXTG)
pc16_gghh_d16_0h0l1d.mod: d16_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd16_1h0.mod: abbrevd16_1h0.$(OBJEXTG)
pc16_gghh_d16_1h0l1.mod: d16_1h0l1.$(OBJEXTG)
pc16_gghh_d16_1h0l1d.mod: d16_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd16_2h0.mod: abbrevd16_2h0.$(OBJEXTG)
pc16_gghh_d16_2h0l1.mod: d16_2h0l1.$(OBJEXTG)
pc16_gghh_d16_2h0l1d.mod: d16_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd18_0h0.mod: abbrevd18_0h0.$(OBJEXTG)
pc16_gghh_d18_0h0l1.mod: d18_0h0l1.$(OBJEXTG)
pc16_gghh_d18_0h0l1d.mod: d18_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd18_1h0.mod: abbrevd18_1h0.$(OBJEXTG)
pc16_gghh_d18_1h0l1.mod: d18_1h0l1.$(OBJEXTG)
pc16_gghh_d18_1h0l1d.mod: d18_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd18_2h0.mod: abbrevd18_2h0.$(OBJEXTG)
pc16_gghh_d18_2h0l1.mod: d18_2h0l1.$(OBJEXTG)
pc16_gghh_d18_2h0l1d.mod: d18_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd22_0h0.mod: abbrevd22_0h0.$(OBJEXTG)
pc16_gghh_d22_0h0l1.mod: d22_0h0l1.$(OBJEXTG)
pc16_gghh_d22_0h0l1d.mod: d22_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd22_1h0.mod: abbrevd22_1h0.$(OBJEXTG)
pc16_gghh_d22_1h0l1.mod: d22_1h0l1.$(OBJEXTG)
pc16_gghh_d22_1h0l1d.mod: d22_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd22_2h0.mod: abbrevd22_2h0.$(OBJEXTG)
pc16_gghh_d22_2h0l1.mod: d22_2h0l1.$(OBJEXTG)
pc16_gghh_d22_2h0l1d.mod: d22_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd23_0h0.mod: abbrevd23_0h0.$(OBJEXTG)
pc16_gghh_d23_0h0l1.mod: d23_0h0l1.$(OBJEXTG)
pc16_gghh_d23_0h0l1d.mod: d23_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd23_1h0.mod: abbrevd23_1h0.$(OBJEXTG)
pc16_gghh_d23_1h0l1.mod: d23_1h0l1.$(OBJEXTG)
pc16_gghh_d23_1h0l1d.mod: d23_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd23_2h0.mod: abbrevd23_2h0.$(OBJEXTG)
pc16_gghh_d23_2h0l1.mod: d23_2h0l1.$(OBJEXTG)
pc16_gghh_d23_2h0l1d.mod: d23_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd27_0h0.mod: abbrevd27_0h0.$(OBJEXTG)
pc16_gghh_d27_0h0l1.mod: d27_0h0l1.$(OBJEXTG)
pc16_gghh_d27_0h0l1d.mod: d27_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd27_1h0.mod: abbrevd27_1h0.$(OBJEXTG)
pc16_gghh_d27_1h0l1.mod: d27_1h0l1.$(OBJEXTG)
pc16_gghh_d27_1h0l1d.mod: d27_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd27_2h0.mod: abbrevd27_2h0.$(OBJEXTG)
pc16_gghh_d27_2h0l1.mod: d27_2h0l1.$(OBJEXTG)
pc16_gghh_d27_2h0l1d.mod: d27_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd29_0h0.mod: abbrevd29_0h0.$(OBJEXTG)
pc16_gghh_d29_0h0l1.mod: d29_0h0l1.$(OBJEXTG)
pc16_gghh_d29_0h0l1d.mod: d29_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd29_1h0.mod: abbrevd29_1h0.$(OBJEXTG)
pc16_gghh_d29_1h0l1.mod: d29_1h0l1.$(OBJEXTG)
pc16_gghh_d29_1h0l1d.mod: d29_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd29_2h0.mod: abbrevd29_2h0.$(OBJEXTG)
pc16_gghh_d29_2h0l1.mod: d29_2h0l1.$(OBJEXTG)
pc16_gghh_d29_2h0l1d.mod: d29_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd31_0h0.mod: abbrevd31_0h0.$(OBJEXTG)
pc16_gghh_d31_0h0l1.mod: d31_0h0l1.$(OBJEXTG)
pc16_gghh_d31_0h0l1d.mod: d31_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd31_1h0.mod: abbrevd31_1h0.$(OBJEXTG)
pc16_gghh_d31_1h0l1.mod: d31_1h0l1.$(OBJEXTG)
pc16_gghh_d31_1h0l1d.mod: d31_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd31_2h0.mod: abbrevd31_2h0.$(OBJEXTG)
pc16_gghh_d31_2h0l1.mod: d31_2h0l1.$(OBJEXTG)
pc16_gghh_d31_2h0l1d.mod: d31_2h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd33_0h0.mod: abbrevd33_0h0.$(OBJEXTG)
pc16_gghh_d33_0h0l1.mod: d33_0h0l1.$(OBJEXTG)
pc16_gghh_d33_0h0l1d.mod: d33_0h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd33_1h0.mod: abbrevd33_1h0.$(OBJEXTG)
pc16_gghh_d33_1h0l1.mod: d33_1h0l1.$(OBJEXTG)
pc16_gghh_d33_1h0l1d.mod: d33_1h0l1d.$(OBJEXTG)
pc16_gghh_abbrevd33_2h0.mod: abbrevd33_2h0.$(OBJEXTG)
pc16_gghh_d33_2h0l1.mod: d33_2h0l1.$(OBJEXTG)
pc16_gghh_d33_2h0l1d.mod: d33_2h0l1d.$(OBJEXTG)
pc16_gghh_amplitudeh0_0.mod: amplitudeh0_0.$(OBJEXTG)
pc16_gghh_amplitudeh0_1.mod: amplitudeh0_1.$(OBJEXTG)
pc16_gghh_amplitudeh0_2.mod: amplitudeh0_2.$(OBJEXTG)
pc16_gghh_globalsh0.mod: globals.$(OBJEXTG)
