# vim: ts=3:sw=3


include ../Makefile.conf


compile: source amplitude0_0.a amplitude0_1.a amplitude0_2.a


-include Makefile.source

HAVE_MAKEFILE_SOURCE=$(if $(wildcard Makefile.source),1,0)
HAVE_ORIG_DIAGRAM_FILE=$(if $(shell test -e ../diagrams-1.hh && head -n 100 ../diagrams-1.hh | grep 'Local'),1,0)

OBJECTS_0= \
	globals.o amplitudeh0_0.o golem95_0h0.o \
	diagramsl0_0.o \
	abbrevd1_0h0.o \
	abbrevd2_0h0.o \
	abbrevd3_0h0.o \
	abbrevd4_0h0.o \
	abbrevd5_0h0.o \
	abbrevd7_0h0.o \
	abbrevd8_0h0.o \
	abbrevd10_0h0.o \
	abbrevd12_0h0.o \
	abbrevd14_0h0.o \
	abbrevd16_0h0.o \
	abbrevd18_0h0.o \
	abbrevd22_0h0.o \
	abbrevd23_0h0.o \
	abbrevd27_0h0.o \
	abbrevd29_0h0.o \
	abbrevd31_0h0.o \
	abbrevd33_0h0.o \
	d1_0h0l1.o \
	d1_0h0l1d.o \
	d2_0h0l1.o \
	d2_0h0l1d.o \
	d3_0h0l1.o \
	d3_0h0l1d.o \
	d4_0h0l1.o \
	d4_0h0l1d.o \
	d5_0h0l1.o \
	d5_0h0l1d.o \
	d7_0h0l1.o \
	d7_0h0l1d.o \
	d8_0h0l1.o \
	d8_0h0l1d.o \
	d10_0h0l1.o \
	d10_0h0l1d.o \
	d12_0h0l1.o \
	d12_0h0l1d.o \
	d14_0h0l1.o \
	d14_0h0l1d.o \
	d16_0h0l1.o \
	d16_0h0l1d.o \
	d18_0h0l1.o \
	d18_0h0l1d.o \
	d22_0h0l1.o \
	d22_0h0l1d.o \
	d23_0h0l1.o \
	d23_0h0l1d.o \
	d27_0h0l1.o \
	d27_0h0l1d.o \
	d29_0h0l1.o \
	d29_0h0l1d.o \
	d31_0h0l1.o \
	d31_0h0l1d.o \
	d33_0h0l1.o \
	d33_0h0l1d.o
GENERATED_SRC_0= \
	diagramsl0_0.f90 \
	abbrevd1_0h0.f90 \
	abbrevd2_0h0.f90 \
	abbrevd3_0h0.f90 \
	abbrevd4_0h0.f90 \
	abbrevd5_0h0.f90 \
	abbrevd7_0h0.f90 \
	abbrevd8_0h0.f90 \
	abbrevd10_0h0.f90 \
	abbrevd12_0h0.f90 \
	abbrevd14_0h0.f90 \
	abbrevd16_0h0.f90 \
	abbrevd18_0h0.f90 \
	abbrevd22_0h0.f90 \
	abbrevd23_0h0.f90 \
	abbrevd27_0h0.f90 \
	abbrevd29_0h0.f90 \
	abbrevd31_0h0.f90 \
	abbrevd33_0h0.f90 \
	d1_0h0l1.f90 \
	d1_0h0l1d.f90 \
	d2_0h0l1.f90 \
	d2_0h0l1d.f90 \
	d3_0h0l1.f90 \
	d3_0h0l1d.f90 \
	d4_0h0l1.f90 \
	d4_0h0l1d.f90 \
	d5_0h0l1.f90 \
	d5_0h0l1d.f90 \
	d7_0h0l1.f90 \
	d7_0h0l1d.f90 \
	d8_0h0l1.f90 \
	d8_0h0l1d.f90 \
	d10_0h0l1.f90 \
	d10_0h0l1d.f90 \
	d12_0h0l1.f90 \
	d12_0h0l1d.f90 \
	d14_0h0l1.f90 \
	d14_0h0l1d.f90 \
	d16_0h0l1.f90 \
	d16_0h0l1d.f90 \
	d18_0h0l1.f90 \
	d18_0h0l1d.f90 \
	d22_0h0l1.f90 \
	d22_0h0l1d.f90 \
	d23_0h0l1.f90 \
	d23_0h0l1d.f90 \
	d27_0h0l1.f90 \
	d27_0h0l1d.f90 \
	d29_0h0l1.f90 \
	d29_0h0l1d.f90 \
	d31_0h0l1.f90 \
	d31_0h0l1d.f90 \
	d33_0h0l1.f90 \
	d33_0h0l1d.f90


OBJECTS_1= \
	globals.o amplitudeh0_1.o golem95_1h0.o \
	diagramsl0_1.o \
	abbrevd1_1h0.o \
	abbrevd2_1h0.o \
	abbrevd3_1h0.o \
	abbrevd4_1h0.o \
	abbrevd5_1h0.o \
	abbrevd7_1h0.o \
	abbrevd8_1h0.o \
	abbrevd10_1h0.o \
	abbrevd12_1h0.o \
	abbrevd14_1h0.o \
	abbrevd16_1h0.o \
	abbrevd18_1h0.o \
	abbrevd22_1h0.o \
	abbrevd23_1h0.o \
	abbrevd27_1h0.o \
	abbrevd29_1h0.o \
	abbrevd31_1h0.o \
	abbrevd33_1h0.o \
	d1_1h0l1.o \
	d1_1h0l1d.o \
	d2_1h0l1.o \
	d2_1h0l1d.o \
	d3_1h0l1.o \
	d3_1h0l1d.o \
	d4_1h0l1.o \
	d4_1h0l1d.o \
	d5_1h0l1.o \
	d5_1h0l1d.o \
	d7_1h0l1.o \
	d7_1h0l1d.o \
	d8_1h0l1.o \
	d8_1h0l1d.o \
	d10_1h0l1.o \
	d10_1h0l1d.o \
	d12_1h0l1.o \
	d12_1h0l1d.o \
	d14_1h0l1.o \
	d14_1h0l1d.o \
	d16_1h0l1.o \
	d16_1h0l1d.o \
	d18_1h0l1.o \
	d18_1h0l1d.o \
	d22_1h0l1.o \
	d22_1h0l1d.o \
	d23_1h0l1.o \
	d23_1h0l1d.o \
	d27_1h0l1.o \
	d27_1h0l1d.o \
	d29_1h0l1.o \
	d29_1h0l1d.o \
	d31_1h0l1.o \
	d31_1h0l1d.o \
	d33_1h0l1.o \
	d33_1h0l1d.o
GENERATED_SRC_1= \
	diagramsl0_1.f90 \
	abbrevd1_1h0.f90 \
	abbrevd2_1h0.f90 \
	abbrevd3_1h0.f90 \
	abbrevd4_1h0.f90 \
	abbrevd5_1h0.f90 \
	abbrevd7_1h0.f90 \
	abbrevd8_1h0.f90 \
	abbrevd10_1h0.f90 \
	abbrevd12_1h0.f90 \
	abbrevd14_1h0.f90 \
	abbrevd16_1h0.f90 \
	abbrevd18_1h0.f90 \
	abbrevd22_1h0.f90 \
	abbrevd23_1h0.f90 \
	abbrevd27_1h0.f90 \
	abbrevd29_1h0.f90 \
	abbrevd31_1h0.f90 \
	abbrevd33_1h0.f90 \
	d1_1h0l1.f90 \
	d1_1h0l1d.f90 \
	d2_1h0l1.f90 \
	d2_1h0l1d.f90 \
	d3_1h0l1.f90 \
	d3_1h0l1d.f90 \
	d4_1h0l1.f90 \
	d4_1h0l1d.f90 \
	d5_1h0l1.f90 \
	d5_1h0l1d.f90 \
	d7_1h0l1.f90 \
	d7_1h0l1d.f90 \
	d8_1h0l1.f90 \
	d8_1h0l1d.f90 \
	d10_1h0l1.f90 \
	d10_1h0l1d.f90 \
	d12_1h0l1.f90 \
	d12_1h0l1d.f90 \
	d14_1h0l1.f90 \
	d14_1h0l1d.f90 \
	d16_1h0l1.f90 \
	d16_1h0l1d.f90 \
	d18_1h0l1.f90 \
	d18_1h0l1d.f90 \
	d22_1h0l1.f90 \
	d22_1h0l1d.f90 \
	d23_1h0l1.f90 \
	d23_1h0l1d.f90 \
	d27_1h0l1.f90 \
	d27_1h0l1d.f90 \
	d29_1h0l1.f90 \
	d29_1h0l1d.f90 \
	d31_1h0l1.f90 \
	d31_1h0l1d.f90 \
	d33_1h0l1.f90 \
	d33_1h0l1d.f90


OBJECTS_2= \
	globals.o amplitudeh0_2.o golem95_2h0.o \
	diagramsl0_2.o \
	abbrevd1_2h0.o \
	abbrevd2_2h0.o \
	abbrevd3_2h0.o \
	abbrevd4_2h0.o \
	abbrevd5_2h0.o \
	abbrevd7_2h0.o \
	abbrevd8_2h0.o \
	abbrevd10_2h0.o \
	abbrevd12_2h0.o \
	abbrevd14_2h0.o \
	abbrevd16_2h0.o \
	abbrevd18_2h0.o \
	abbrevd22_2h0.o \
	abbrevd23_2h0.o \
	abbrevd27_2h0.o \
	abbrevd29_2h0.o \
	abbrevd31_2h0.o \
	abbrevd33_2h0.o \
	d1_2h0l1.o \
	d1_2h0l1d.o \
	d2_2h0l1.o \
	d2_2h0l1d.o \
	d3_2h0l1.o \
	d3_2h0l1d.o \
	d4_2h0l1.o \
	d4_2h0l1d.o \
	d5_2h0l1.o \
	d5_2h0l1d.o \
	d7_2h0l1.o \
	d7_2h0l1d.o \
	d8_2h0l1.o \
	d8_2h0l1d.o \
	d10_2h0l1.o \
	d10_2h0l1d.o \
	d12_2h0l1.o \
	d12_2h0l1d.o \
	d14_2h0l1.o \
	d14_2h0l1d.o \
	d16_2h0l1.o \
	d16_2h0l1d.o \
	d18_2h0l1.o \
	d18_2h0l1d.o \
	d22_2h0l1.o \
	d22_2h0l1d.o \
	d23_2h0l1.o \
	d23_2h0l1d.o \
	d27_2h0l1.o \
	d27_2h0l1d.o \
	d29_2h0l1.o \
	d29_2h0l1d.o \
	d31_2h0l1.o \
	d31_2h0l1d.o \
	d33_2h0l1.o \
	d33_2h0l1d.o
GENERATED_SRC_2= \
	diagramsl0_2.f90 \
	abbrevd1_2h0.f90 \
	abbrevd2_2h0.f90 \
	abbrevd3_2h0.f90 \
	abbrevd4_2h0.f90 \
	abbrevd5_2h0.f90 \
	abbrevd7_2h0.f90 \
	abbrevd8_2h0.f90 \
	abbrevd10_2h0.f90 \
	abbrevd12_2h0.f90 \
	abbrevd14_2h0.f90 \
	abbrevd16_2h0.f90 \
	abbrevd18_2h0.f90 \
	abbrevd22_2h0.f90 \
	abbrevd23_2h0.f90 \
	abbrevd27_2h0.f90 \
	abbrevd29_2h0.f90 \
	abbrevd31_2h0.f90 \
	abbrevd33_2h0.f90 \
	d1_2h0l1.f90 \
	d1_2h0l1d.f90 \
	d2_2h0l1.f90 \
	d2_2h0l1d.f90 \
	d3_2h0l1.f90 \
	d3_2h0l1d.f90 \
	d4_2h0l1.f90 \
	d4_2h0l1d.f90 \
	d5_2h0l1.f90 \
	d5_2h0l1d.f90 \
	d7_2h0l1.f90 \
	d7_2h0l1d.f90 \
	d8_2h0l1.f90 \
	d8_2h0l1d.f90 \
	d10_2h0l1.f90 \
	d10_2h0l1d.f90 \
	d12_2h0l1.f90 \
	d12_2h0l1d.f90 \
	d14_2h0l1.f90 \
	d14_2h0l1d.f90 \
	d16_2h0l1.f90 \
	d16_2h0l1d.f90 \
	d18_2h0l1.f90 \
	d18_2h0l1d.f90 \
	d22_2h0l1.f90 \
	d22_2h0l1d.f90 \
	d23_2h0l1.f90 \
	d23_2h0l1d.f90 \
	d27_2h0l1.f90 \
	d27_2h0l1d.f90 \
	d29_2h0l1.f90 \
	d29_2h0l1d.f90 \
	d31_2h0l1.f90 \
	d31_2h0l1d.f90 \
	d33_2h0l1.f90 \
	d33_2h0l1d.f90

.PHONY: compile source clean very-clean doc convert
.SUFFIXES:

TEMPFILE:=$(shell mktemp -u -t gosam.tempfile.XXXXXX || echo gosam.tempfile.tmp)

convert:
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif

ifeq ($(HAVE_MAKEFILE_SOURCE),1)
source: convert  $(SOURCE_TREE) $(SOURCE_VIRT)
else
source:
endif




d1_0h0l1: d1_0h0l1.f90 abbrevd1_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d1_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d1_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd1_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd1_0h0.o -I../common abbrevd1_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d1_0h0l1.o -I../common d1_0h0l1.f90
endif

d1_1h0l1: d1_1h0l1.f90 abbrevd1_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d1_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d1_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd1_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd1_1h0.o -I../common abbrevd1_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d1_1h0l1.o -I../common d1_1h0l1.f90
endif

d1_2h0l1: d1_2h0l1.f90 abbrevd1_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d1_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d1_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd1_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd1_2h0.o -I../common abbrevd1_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d1_2h0l1.o -I../common d1_2h0l1.f90
endif



d2_0h0l1: d2_0h0l1.f90 abbrevd2_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_0h0.o -I../common abbrevd2_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_0h0l1.o -I../common d2_0h0l1.f90
endif

d2_1h0l1: d2_1h0l1.f90 abbrevd2_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_1h0.o -I../common abbrevd2_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_1h0l1.o -I../common d2_1h0l1.f90
endif

d2_2h0l1: d2_2h0l1.f90 abbrevd2_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_2h0.o -I../common abbrevd2_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_2h0l1.o -I../common d2_2h0l1.f90
endif



d3_0h0l1: d3_0h0l1.f90 abbrevd3_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d3_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d3_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd3_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd3_0h0.o -I../common abbrevd3_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d3_0h0l1.o -I../common d3_0h0l1.f90
endif

d3_1h0l1: d3_1h0l1.f90 abbrevd3_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d3_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d3_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd3_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd3_1h0.o -I../common abbrevd3_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d3_1h0l1.o -I../common d3_1h0l1.f90
endif

d3_2h0l1: d3_2h0l1.f90 abbrevd3_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d3_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d3_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd3_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd3_2h0.o -I../common abbrevd3_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d3_2h0l1.o -I../common d3_2h0l1.f90
endif



d4_0h0l1: d4_0h0l1.f90 abbrevd4_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d4_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d4_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd4_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd4_0h0.o -I../common abbrevd4_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d4_0h0l1.o -I../common d4_0h0l1.f90
endif

d4_1h0l1: d4_1h0l1.f90 abbrevd4_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d4_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d4_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd4_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd4_1h0.o -I../common abbrevd4_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d4_1h0l1.o -I../common d4_1h0l1.f90
endif

d4_2h0l1: d4_2h0l1.f90 abbrevd4_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d4_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d4_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd4_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd4_2h0.o -I../common abbrevd4_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d4_2h0l1.o -I../common d4_2h0l1.f90
endif



d5_0h0l1: d5_0h0l1.f90 abbrevd5_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d5_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d5_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd5_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd5_0h0.o -I../common abbrevd5_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d5_0h0l1.o -I../common d5_0h0l1.f90
endif

d5_1h0l1: d5_1h0l1.f90 abbrevd5_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d5_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d5_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd5_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd5_1h0.o -I../common abbrevd5_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d5_1h0l1.o -I../common d5_1h0l1.f90
endif

d5_2h0l1: d5_2h0l1.f90 abbrevd5_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d5_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d5_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd5_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd5_2h0.o -I../common abbrevd5_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d5_2h0l1.o -I../common d5_2h0l1.f90
endif



d7_0h0l1: d7_0h0l1.f90 abbrevd7_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_0h0.o -I../common abbrevd7_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_0h0l1.o -I../common d7_0h0l1.f90
endif

d7_1h0l1: d7_1h0l1.f90 abbrevd7_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_1h0.o -I../common abbrevd7_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_1h0l1.o -I../common d7_1h0l1.f90
endif

d7_2h0l1: d7_2h0l1.f90 abbrevd7_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_2h0.o -I../common abbrevd7_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_2h0l1.o -I../common d7_2h0l1.f90
endif



d8_0h0l1: d8_0h0l1.f90 abbrevd8_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d8_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d8_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd8_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd8_0h0.o -I../common abbrevd8_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d8_0h0l1.o -I../common d8_0h0l1.f90
endif

d8_1h0l1: d8_1h0l1.f90 abbrevd8_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d8_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d8_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd8_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd8_1h0.o -I../common abbrevd8_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d8_1h0l1.o -I../common d8_1h0l1.f90
endif

d8_2h0l1: d8_2h0l1.f90 abbrevd8_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d8_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d8_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd8_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd8_2h0.o -I../common abbrevd8_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d8_2h0l1.o -I../common d8_2h0l1.f90
endif



d10_0h0l1: d10_0h0l1.f90 abbrevd10_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d10_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d10_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd10_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd10_0h0.o -I../common abbrevd10_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d10_0h0l1.o -I../common d10_0h0l1.f90
endif

d10_1h0l1: d10_1h0l1.f90 abbrevd10_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d10_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d10_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd10_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd10_1h0.o -I../common abbrevd10_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d10_1h0l1.o -I../common d10_1h0l1.f90
endif

d10_2h0l1: d10_2h0l1.f90 abbrevd10_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d10_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d10_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd10_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd10_2h0.o -I../common abbrevd10_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d10_2h0l1.o -I../common d10_2h0l1.f90
endif



d12_0h0l1: d12_0h0l1.f90 abbrevd12_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d12_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d12_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd12_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd12_0h0.o -I../common abbrevd12_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d12_0h0l1.o -I../common d12_0h0l1.f90
endif

d12_1h0l1: d12_1h0l1.f90 abbrevd12_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d12_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d12_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd12_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd12_1h0.o -I../common abbrevd12_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d12_1h0l1.o -I../common d12_1h0l1.f90
endif

d12_2h0l1: d12_2h0l1.f90 abbrevd12_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d12_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d12_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd12_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd12_2h0.o -I../common abbrevd12_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d12_2h0l1.o -I../common d12_2h0l1.f90
endif



d14_0h0l1: d14_0h0l1.f90 abbrevd14_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d14_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d14_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd14_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd14_0h0.o -I../common abbrevd14_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d14_0h0l1.o -I../common d14_0h0l1.f90
endif

d14_1h0l1: d14_1h0l1.f90 abbrevd14_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d14_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d14_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd14_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd14_1h0.o -I../common abbrevd14_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d14_1h0l1.o -I../common d14_1h0l1.f90
endif

d14_2h0l1: d14_2h0l1.f90 abbrevd14_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d14_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d14_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd14_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd14_2h0.o -I../common abbrevd14_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d14_2h0l1.o -I../common d14_2h0l1.f90
endif



d16_0h0l1: d16_0h0l1.f90 abbrevd16_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d16_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d16_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd16_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd16_0h0.o -I../common abbrevd16_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d16_0h0l1.o -I../common d16_0h0l1.f90
endif

d16_1h0l1: d16_1h0l1.f90 abbrevd16_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d16_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d16_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd16_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd16_1h0.o -I../common abbrevd16_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d16_1h0l1.o -I../common d16_1h0l1.f90
endif

d16_2h0l1: d16_2h0l1.f90 abbrevd16_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d16_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d16_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd16_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd16_2h0.o -I../common abbrevd16_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d16_2h0l1.o -I../common d16_2h0l1.f90
endif



d18_0h0l1: d18_0h0l1.f90 abbrevd18_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d18_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d18_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd18_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd18_0h0.o -I../common abbrevd18_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d18_0h0l1.o -I../common d18_0h0l1.f90
endif

d18_1h0l1: d18_1h0l1.f90 abbrevd18_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d18_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d18_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd18_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd18_1h0.o -I../common abbrevd18_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d18_1h0l1.o -I../common d18_1h0l1.f90
endif

d18_2h0l1: d18_2h0l1.f90 abbrevd18_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d18_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d18_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd18_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd18_2h0.o -I../common abbrevd18_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d18_2h0l1.o -I../common d18_2h0l1.f90
endif



d22_0h0l1: d22_0h0l1.f90 abbrevd22_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d22_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d22_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd22_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd22_0h0.o -I../common abbrevd22_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d22_0h0l1.o -I../common d22_0h0l1.f90
endif

d22_1h0l1: d22_1h0l1.f90 abbrevd22_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d22_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d22_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd22_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd22_1h0.o -I../common abbrevd22_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d22_1h0l1.o -I../common d22_1h0l1.f90
endif

d22_2h0l1: d22_2h0l1.f90 abbrevd22_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d22_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d22_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd22_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd22_2h0.o -I../common abbrevd22_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d22_2h0l1.o -I../common d22_2h0l1.f90
endif



d23_0h0l1: d23_0h0l1.f90 abbrevd23_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d23_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d23_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd23_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd23_0h0.o -I../common abbrevd23_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d23_0h0l1.o -I../common d23_0h0l1.f90
endif

d23_1h0l1: d23_1h0l1.f90 abbrevd23_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d23_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d23_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd23_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd23_1h0.o -I../common abbrevd23_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d23_1h0l1.o -I../common d23_1h0l1.f90
endif

d23_2h0l1: d23_2h0l1.f90 abbrevd23_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d23_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d23_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd23_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd23_2h0.o -I../common abbrevd23_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d23_2h0l1.o -I../common d23_2h0l1.f90
endif



d27_0h0l1: d27_0h0l1.f90 abbrevd27_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d27_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d27_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd27_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd27_0h0.o -I../common abbrevd27_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d27_0h0l1.o -I../common d27_0h0l1.f90
endif

d27_1h0l1: d27_1h0l1.f90 abbrevd27_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d27_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d27_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd27_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd27_1h0.o -I../common abbrevd27_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d27_1h0l1.o -I../common d27_1h0l1.f90
endif

d27_2h0l1: d27_2h0l1.f90 abbrevd27_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d27_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d27_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd27_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd27_2h0.o -I../common abbrevd27_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d27_2h0l1.o -I../common d27_2h0l1.f90
endif



d29_0h0l1: d29_0h0l1.f90 abbrevd29_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d29_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d29_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd29_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd29_0h0.o -I../common abbrevd29_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d29_0h0l1.o -I../common d29_0h0l1.f90
endif

d29_1h0l1: d29_1h0l1.f90 abbrevd29_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d29_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d29_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd29_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd29_1h0.o -I../common abbrevd29_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d29_1h0l1.o -I../common d29_1h0l1.f90
endif

d29_2h0l1: d29_2h0l1.f90 abbrevd29_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d29_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d29_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd29_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd29_2h0.o -I../common abbrevd29_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d29_2h0l1.o -I../common d29_2h0l1.f90
endif



d31_0h0l1: d31_0h0l1.f90 abbrevd31_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d31_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d31_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd31_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd31_0h0.o -I../common abbrevd31_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d31_0h0l1.o -I../common d31_0h0l1.f90
endif

d31_1h0l1: d31_1h0l1.f90 abbrevd31_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d31_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d31_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd31_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd31_1h0.o -I../common abbrevd31_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d31_1h0l1.o -I../common d31_1h0l1.f90
endif

d31_2h0l1: d31_2h0l1.f90 abbrevd31_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d31_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d31_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd31_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd31_2h0.o -I../common abbrevd31_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d31_2h0l1.o -I../common d31_2h0l1.f90
endif



d33_0h0l1: d33_0h0l1.f90 abbrevd33_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d33_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d33_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd33_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd33_0h0.o -I../common abbrevd33_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d33_0h0l1.o -I../common d33_0h0l1.f90
endif

d33_1h0l1: d33_1h0l1.f90 abbrevd33_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d33_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d33_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd33_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd33_1h0.o -I../common abbrevd33_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d33_1h0l1.o -I../common d33_1h0l1.f90
endif

d33_2h0l1: d33_2h0l1.f90 abbrevd33_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d33_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d33_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd33_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd33_2h0.o -I../common abbrevd33_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d33_2h0l1.o -I../common d33_2h0l1.f90
endif



$(OBJECTS_0): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<

$(OBJECTS_1): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<

$(OBJECTS_2): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<



amplitude0_0.a: $(OBJECTS_0)
	$(Q) ar rs $@ $+
amplitude0_1.a: $(OBJECTS_1)
	$(Q) ar rs $@ $+
amplitude0_2.a: $(OBJECTS_2)
	$(Q) ar rs $@ $+


doc:

clean:
	$(Q)$(FIND) $(FIND_OPT) . \( -name '*.o' \
		-or -name '*.mod' -or -name '*.a' -or -name '*.so' \) \
		-exec rm \{} \;

very-clean: clean
	$(Q)rm -f filelist-source
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(Q)$(FIND) $(FIND_OPT) . \( \
		-name 'd*h0l[01].f90' \
		-or -name 'd*h0l[01]fr5.f90' \
		-or -name 'd*h0l[014]*.txt' \
		-or -name 'd*h0l1[123dmu]*.txt' \
		-or -name 'd*h0l1[123dmu]*.f90' \
		-or -name 'd*h0l[01]c.txt' \
		-or -name 'd*h0l[01]c.f90' \
		-or -name 'd*h0l[01]d.txt' \
		-or -name 'd*h0l[01]d.hh' \
		-or -name 'd*h0l[01].hh' \
		-or -name 'd*h0l1d.txt' \
		-or -name 'd*h0l1d.f90' \
		-or -name 'd*h0l[01]-fr.txt' \
		-or -name 'd*h0l[01].dat' \
		-or -name 'd*h0l[01].abb' \
		-or -name 'diagramsl0_0.f90' \
		-or -name 'abbrevd*h0.f90' \
		-or -name 'd*h0l[01].prc' \
		-or -name 'borndiag*.prc' \
		-or -name 'born*.txt' \
		-or -name 'born*.dat' \
		-or -name '*-stamp'  \
		-or -name 'lightconedecomp.prc' \
		\) -exec rm \{} \;
endif

filelist-source: source
	$(Q)$(FIND) $(FIND_OPT) . \( \
		-name '*.f90' \
		-or -name 'Makefile' \
		-or -name 'Makefile.dep' \
		\) -print > $@

include Makefile.dep
