[% ' vim: ts=3:sw=3:syntax=golem
	' %]
# Module Dependencies:[%
@for each o lo obj var=O %][%
   @if extension pjfry %]
pjfry95pg.[%O%]: precision_pjfry.[%O%]
pjfry_comb.[%O%]: pjfry95pg.[%O%] precision_pjfry.[%O%][%
   @end @if %]
accu.[%O%]: config.[%O%]
model.[%O%]: config.[%O%]
color.[%O%]: config.[%O%] model.[%O%]
rambo.[%O%]: config.[%O%] model.[%O%]
globalsl1.[%O%]: config.[%O%] color.[%O%]
util.[%O%]: config.[%O%] color.[%O%]
kinematics.[%O%]: config.[%O%] model.[%O%] scalar_cache.[%O%]
dipoles.[%O%]: config.[%O%] color.[%O%] model.[%O%] kinematics.[%O%][%
	@select r2
	@case implicit explicit off %]
groups.[%O%]: config.[%O%] model.[%O%] kinematics.[%O%] globalsl1.[%O%][%
   	@if extension pjfry %] \
	pjfry95pg.[%O%] pjfry_comb.[%O%] precision_pjfry.[%O%][%
	   @end @if %][%
	@end @select %][%
   @if internal CUSTOM_SPIN2_PROP %]
custompropagator.[%O%]: config.[%O%] model.[%O%][%
   @end @if %][%
@end @for %]
