[% ' vim: ts=3:sw=3:syntax=golem
	' %]
OBJEXT ?=o
OBJEXTG=[%@if extension autotools %]lo[% @else %]$(OBJEXT)[%@end @if%]
# Module Dependencies:[%
@for each $(OBJEXTG) var=O %][%
   @if extension pjfry %]
pjfry95pg.[%O%]: precision_pjfry.[%O%]
pjfry_comb.[%O%]: pjfry95pg.[%O%] precision_pjfry.[%O%][%
   @end @if %]
accu.[%O%]: config.[%O%]
model.[%O%]: config.[%O%]
color.[%O%]: config.[%O%] model.[%O%]
rambo.[%O%]: config.[%O%] model.[%O%]
globalsl1.[%O%]: config.[%O%] color.[%O%]
util.[%O%]: config.[%O%] color.[%O%]
kinematics.[%O%]: config.[%O%] model.[%O%] scalar_cache.[%O%]
dipoles.[%O%]: config.[%O%] color.[%O%] model.[%O%] kinematics.[%O%][%
	@select r2
	@case implicit explicit off %]
groups.[%O%]: config.[%O%] model.[%O%] kinematics.[%O%] globalsl1.[%O%][%
   	@if extension pjfry %] \
	pjfry95pg.[%O%] pjfry_comb.[%O%] precision_pjfry.[%O%][%
	   @end @if %][%
	@end @select %][%
   @if internal CUSTOM_SPIN2_PROP %]
custompropagator.[%O%]: config.[%O%] model.[%O%][%
   @end @if %][%
@end @for %][%
@for each $(OBJEXTG) var=O %][%
   @if extension pjfry %]
[% process_name asprefix=\_ %]pjfry95pg.mod: precision_pjfry.[%O%] pjfry95pg.[%O%]
[% process_name asprefix=\_ %]pjfry_comb: pjfry_comb.[%O%] pjfry95pg.[%O%] precision_pjfry.[%O%][%
@end @if %]
[% process_name asprefix=\_ %]accu.mod: accu.[%O%] config.[%O%]
[% process_name asprefix=\_ %]color.mod: color.[%O%]
[% process_name asprefix=\_ %]config.mod: config.[%O%]
[% process_name asprefix=\_ %]version.mod: version.[%O%]
[% process_name asprefix=\_ %]model.mod: model.[%O%] config.[%O%]
[% process_name asprefix=\_ %]dipoles.mod: dipoles.[%O%]
[% process_name asprefix=\_ %]rambo.mod: rambo.[%O%] config.[%O%] model.[%O%]
[% process_name asprefix=\_ %]globalsl1.mod:  globalsl1.[%O%] config.[%O%] color.[%O%]
[% process_name asprefix=\_ %]util.mod: util.[%O%] config.[%O%] color.[%O%]
[% process_name asprefix=\_ %]kinematics.mod: kinematics.[%O%] config.[%O%] model.[%O%] scalar_cache.[%O%]
[% process_name asprefix=\_ %]scalar_cache.mod: scalar_cache.[%O%]
[% process_name asprefix=\_ %]dipoles.mod: dipoles.[%O%] config.[%O%] color.[%O%] model.[%O%] kinematics.[%O%][%
	@select r2
	@case implicit explicit off %]
[% process_name asprefix=\_ %]groups.mod: groups.[%O%] config.[%O%] model.[%O%] kinematics.[%O%] globalsl1.[%O%][%
   	@if extension pjfry %] \
	pjfry95pg.[%O%] pjfry_comb.[%O%] precision_pjfry.[%O%][%
	   @end @if %][%
	@end @select %][%
   @if internal CUSTOM_SPIN2_PROP %]
[% process_name asprefix=\_ %]custompropagator.mod: custompropagator.[%O%] config.[%O%] model.[%O%][%
   @end @if %][%
@end @for %]
