[% ' vim: ts=3:sw=3:syntax=golem
	' %]
OBJEXT ?=o
OBJEXTG=[%@if extension autotools %]lo[% @else %]$(OBJEXT)[%@end @if%]
# Module Dependencies:[%
@for each $(OBJEXTG) var=O %]
accu.[%O%]: config.[%O%]
model.[%O%]: config.[%O%]
color.[%O%]: config.[%O%] model.[%O%]
rambo.[%O%]: config.[%O%] model.[%O%]
globalsl1.[%O%]: config.[%O%] color.[%O%]
util.[%O%]: config.[%O%] color.[%O%]
kinematics.[%O%]: config.[%O%] model.[%O%] scalar_cache.[%O%]
dipoles.[%O%]: config.[%O%] color.[%O%] model.[%O%] kinematics.[%O%][%
	@select r2
	@case implicit explicit off %]
groups.[%O%]: config.[%O%] model.[%O%] kinematics.[%O%] globalsl1.[%O%][%
	@end @select %][%
   @if internal CUSTOM_SPIN2_PROP %]
custompropagator.[%O%]: config.[%O%] model.[%O%][%
   @end @if %][%
   @if extension quadruple %]
accu_qp.[%O%]: config.[%O%]
model_qp.[%O%]: config.[%O%]
color_qp.[%O%]: config.[%O%] model_qp.[%O%]
rambo_qp.[%O%]: config.[%O%] model_qp.[%O%]
globalsl1_qp.[%O%]: config.[%O%] color_qp.[%O%]
util_qp.[%O%]: config.[%O%] color_qp.[%O%]
kinematics_qp.[%O%]: config.[%O%] model_qp.[%O%] scalar_cache.[%O%]
dipoles_qp.[%O%]: config.[%O%] color_qp.[%O%] model_qp.[%O%] kinematics_qp.[%O%][%
@end @if %][%
@end @for %][%
@for each $(OBJEXTG) var=O %]
[% process_name asprefix=\_ %]accu.mod: accu.[%O%] config.[%O%]
[% process_name asprefix=\_ %]color.mod: color.[%O%]
[% process_name asprefix=\_ %]config.mod: config.[%O%]
[% process_name asprefix=\_ %]version.mod: version.[%O%]
[% process_name asprefix=\_ %]model.mod: model.[%O%] config.[%O%]
[% process_name asprefix=\_ %]rambo.mod: rambo.[%O%] config.[%O%] model.[%O%]
[% process_name asprefix=\_ %]globalsl1.mod:  globalsl1.[%O%] config.[%O%] color.[%O%]
[% process_name asprefix=\_ %]util.mod: util.[%O%] config.[%O%] color.[%O%]
[% process_name asprefix=\_ %]kinematics.mod: kinematics.[%O%] config.[%O%] model.[%O%] scalar_cache.[%O%]
[% process_name asprefix=\_ %]scalar_cache.mod: scalar_cache.[%O%]
[% process_name asprefix=\_ %]dipoles.mod: dipoles.[%O%] config.[%O%] color.[%O%] model.[%O%] kinematics.[%O%][%
	@select r2
	@case implicit explicit off %]
[% process_name asprefix=\_ %]groups.mod: groups.[%O%] config.[%O%] model.[%O%] kinematics.[%O%] globalsl1.[%O%][%
	@end @select %][%
   @if internal CUSTOM_SPIN2_PROP %]
[% process_name asprefix=\_ %]custompropagator.mod: custompropagator.[%O%] config.[%O%] model.[%O%][%
   @end @if %][%
   @if extension quadruple %]
[% process_name asprefix=\_ %]accu_qp.mod: accu.[%O%] config.[%O%]
[% process_name asprefix=\_ %]color_qp.mod: color.[%O%]
[% process_name asprefix=\_ %]model_qp.mod: model_qp.[%O%] config.[%O%]
[% process_name asprefix=\_ %]rambo_qp.mod: rambo_qp.[%O%] config.[%O%] model_qp.[%O%]
[% process_name asprefix=\_ %]globalsl1_qp.mod:  globalsl1_qp.[%O%] config.[%O%] color_qp.[%O%]
[% process_name asprefix=\_ %]util_qp.mod: util_qp.[%O%] config.[%O%] color_qp.[%O%]
[% process_name asprefix=\_ %]kinematics_qp.mod: kinematics_qp.[%O%] config.[%O%] model_qp.[%O%] scalar_cache.[%O%]
[% process_name asprefix=\_ %]dipoles.mod: dipoles_qp.[%O%] config.[%O%] color_qp.[%O%] model_qp.[%O%] kinematics_qp.[%O%][%
@end @if %][%
@end @for %]
