[% ' vim: ts=3:sw=3:syntax=golem
	' %]
OBJEXT ?=o
# Module Dependencies:[%
@for each $(OBJEXT) lo var=O %]
test.[%O%]: matrix.[%O%][%
	@for crossings %]
[% $_ asprefix=\_ %]matrix.[%O%]: matrix.[%O%][%
	@end @for %][%
@end @for %][%
@for each $(OBJEXT) var=O %]
[% process_name asprefix=\_ %]test.mod: test.[%O%]
[% process_name asprefix=\_ %]matrix.mod: matrix.[%O%][%
@end @for %]
../matrix/libgolem_process_[% process_name asprefix=\_ %]matrix.la: libgolem_process_[% process_name asprefix=\_ %]matrix.la
