[% ' vim: ts=3:sw=3:syntax=golem
	' %]
# Module Dependencies:[%
@for each o lo obj var=O %]
test.[%O%]: matrix.[%O%][%
	@for crossings %]
[% $_ asprefix=\_ %]matrix.[%O%]: matrix.[%O%][%
	@end @for %][%
@end @for %]
