# vim: ts=3:sw=3


include ../Makefile.conf


compile: source amplitude0_0.a amplitude0_1.a amplitude0_2.a


-include Makefile.source

HAVE_MAKEFILE_SOURCE=$(if $(wildcard Makefile.source),1,0)
HAVE_ORIG_DIAGRAM_FILE=$(if $(shell test -e ../diagrams-1.hh && head -n 100 ../diagrams-1.hh | grep 'Local'),1,0)

OBJECTS_0= \
	globals.o amplitudeh0_0.o ninja_0h0.o \
	diagramsl0_0.o \
	abbrevd2_0h0.o \
	abbrevd7_0h0.o \
	abbrevd9_0h0.o \
	abbrevd11_0h0.o \
	abbrevd13_0h0.o \
	d2_0h0l1.o \
	d2_0h0l1d.o \
	d2_0h0l131.o \
	d2_0h0l132.o \
	d2_0h0l121.o \
	d7_0h0l1.o \
	d7_0h0l1d.o \
	d7_0h0l131.o \
	d7_0h0l132.o \
	d7_0h0l121.o \
	d9_0h0l1.o \
	d9_0h0l1d.o \
	d9_0h0l131.o \
	d9_0h0l132.o \
	d9_0h0l121.o \
	d11_0h0l1.o \
	d11_0h0l1d.o \
	d11_0h0l131.o \
	d11_0h0l132.o \
	d11_0h0l121.o \
	d13_0h0l1.o \
	d13_0h0l1d.o \
	d13_0h0l131.o \
	d13_0h0l132.o \
	d13_0h0l121.o
GENERATED_SRC_0= \
	diagramsl0_0.f90 \
	abbrevd2_0h0.f90 \
	abbrevd7_0h0.f90 \
	abbrevd9_0h0.f90 \
	abbrevd11_0h0.f90 \
	abbrevd13_0h0.f90 \
	d2_0h0l1.f90 \
	d2_0h0l1d.f90 \
	d2_0h0l131.f90 \
	d2_0h0l132.f90 \
	d2_0h0l121.f90 \
	d7_0h0l1.f90 \
	d7_0h0l1d.f90 \
	d7_0h0l131.f90 \
	d7_0h0l132.f90 \
	d7_0h0l121.f90 \
	d9_0h0l1.f90 \
	d9_0h0l1d.f90 \
	d9_0h0l131.f90 \
	d9_0h0l132.f90 \
	d9_0h0l121.f90 \
	d11_0h0l1.f90 \
	d11_0h0l1d.f90 \
	d11_0h0l131.f90 \
	d11_0h0l132.f90 \
	d11_0h0l121.f90 \
	d13_0h0l1.f90 \
	d13_0h0l1d.f90 \
	d13_0h0l131.f90 \
	d13_0h0l132.f90 \
	d13_0h0l121.f90


OBJECTS_1= \
	globals.o amplitudeh0_1.o ninja_1h0.o \
	diagramsl0_1.o \
	abbrevd2_1h0.o \
	abbrevd7_1h0.o \
	abbrevd9_1h0.o \
	abbrevd11_1h0.o \
	abbrevd13_1h0.o \
	d2_1h0l1.o \
	d2_1h0l1d.o \
	d2_1h0l131.o \
	d2_1h0l132.o \
	d2_1h0l121.o \
	d7_1h0l1.o \
	d7_1h0l1d.o \
	d7_1h0l131.o \
	d7_1h0l132.o \
	d7_1h0l121.o \
	d9_1h0l1.o \
	d9_1h0l1d.o \
	d9_1h0l131.o \
	d9_1h0l132.o \
	d9_1h0l121.o \
	d11_1h0l1.o \
	d11_1h0l1d.o \
	d11_1h0l131.o \
	d11_1h0l132.o \
	d11_1h0l121.o \
	d13_1h0l1.o \
	d13_1h0l1d.o \
	d13_1h0l131.o \
	d13_1h0l132.o \
	d13_1h0l121.o
GENERATED_SRC_1= \
	diagramsl0_1.f90 \
	abbrevd2_1h0.f90 \
	abbrevd7_1h0.f90 \
	abbrevd9_1h0.f90 \
	abbrevd11_1h0.f90 \
	abbrevd13_1h0.f90 \
	d2_1h0l1.f90 \
	d2_1h0l1d.f90 \
	d2_1h0l131.f90 \
	d2_1h0l132.f90 \
	d2_1h0l121.f90 \
	d7_1h0l1.f90 \
	d7_1h0l1d.f90 \
	d7_1h0l131.f90 \
	d7_1h0l132.f90 \
	d7_1h0l121.f90 \
	d9_1h0l1.f90 \
	d9_1h0l1d.f90 \
	d9_1h0l131.f90 \
	d9_1h0l132.f90 \
	d9_1h0l121.f90 \
	d11_1h0l1.f90 \
	d11_1h0l1d.f90 \
	d11_1h0l131.f90 \
	d11_1h0l132.f90 \
	d11_1h0l121.f90 \
	d13_1h0l1.f90 \
	d13_1h0l1d.f90 \
	d13_1h0l131.f90 \
	d13_1h0l132.f90 \
	d13_1h0l121.f90


OBJECTS_2= \
	globals.o amplitudeh0_2.o ninja_2h0.o \
	diagramsl0_2.o \
	abbrevd2_2h0.o \
	abbrevd7_2h0.o \
	abbrevd9_2h0.o \
	abbrevd11_2h0.o \
	abbrevd13_2h0.o \
	d2_2h0l1.o \
	d2_2h0l1d.o \
	d2_2h0l131.o \
	d2_2h0l132.o \
	d2_2h0l121.o \
	d7_2h0l1.o \
	d7_2h0l1d.o \
	d7_2h0l131.o \
	d7_2h0l132.o \
	d7_2h0l121.o \
	d9_2h0l1.o \
	d9_2h0l1d.o \
	d9_2h0l131.o \
	d9_2h0l132.o \
	d9_2h0l121.o \
	d11_2h0l1.o \
	d11_2h0l1d.o \
	d11_2h0l131.o \
	d11_2h0l132.o \
	d11_2h0l121.o \
	d13_2h0l1.o \
	d13_2h0l1d.o \
	d13_2h0l131.o \
	d13_2h0l132.o \
	d13_2h0l121.o
GENERATED_SRC_2= \
	diagramsl0_2.f90 \
	abbrevd2_2h0.f90 \
	abbrevd7_2h0.f90 \
	abbrevd9_2h0.f90 \
	abbrevd11_2h0.f90 \
	abbrevd13_2h0.f90 \
	d2_2h0l1.f90 \
	d2_2h0l1d.f90 \
	d2_2h0l131.f90 \
	d2_2h0l132.f90 \
	d2_2h0l121.f90 \
	d7_2h0l1.f90 \
	d7_2h0l1d.f90 \
	d7_2h0l131.f90 \
	d7_2h0l132.f90 \
	d7_2h0l121.f90 \
	d9_2h0l1.f90 \
	d9_2h0l1d.f90 \
	d9_2h0l131.f90 \
	d9_2h0l132.f90 \
	d9_2h0l121.f90 \
	d11_2h0l1.f90 \
	d11_2h0l1d.f90 \
	d11_2h0l131.f90 \
	d11_2h0l132.f90 \
	d11_2h0l121.f90 \
	d13_2h0l1.f90 \
	d13_2h0l1d.f90 \
	d13_2h0l131.f90 \
	d13_2h0l132.f90 \
	d13_2h0l121.f90

.PHONY: compile source clean very-clean doc convert
.SUFFIXES:

TEMPFILE:=$(shell mktemp -u -t gosam.tempfile.XXXXXX || echo gosam.tempfile.tmp)

convert:
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif

ifeq ($(HAVE_MAKEFILE_SOURCE),1)
source: convert  $(SOURCE_TREE) $(SOURCE_VIRT)
else
source:
endif




d2_0h0l1: d2_0h0l1.f90 abbrevd2_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_0h0.o -I../common abbrevd2_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_0h0l1.o -I../common d2_0h0l1.f90
endif

d2_1h0l1: d2_1h0l1.f90 abbrevd2_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_1h0.o -I../common abbrevd2_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_1h0l1.o -I../common d2_1h0l1.f90
endif

d2_2h0l1: d2_2h0l1.f90 abbrevd2_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d2_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d2_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd2_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd2_2h0.o -I../common abbrevd2_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d2_2h0l1.o -I../common d2_2h0l1.f90
endif



d7_0h0l1: d7_0h0l1.f90 abbrevd7_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_0h0.o -I../common abbrevd7_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_0h0l1.o -I../common d7_0h0l1.f90
endif

d7_1h0l1: d7_1h0l1.f90 abbrevd7_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_1h0.o -I../common abbrevd7_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_1h0l1.o -I../common d7_1h0l1.f90
endif

d7_2h0l1: d7_2h0l1.f90 abbrevd7_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d7_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d7_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd7_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd7_2h0.o -I../common abbrevd7_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d7_2h0l1.o -I../common d7_2h0l1.f90
endif



d9_0h0l1: d9_0h0l1.f90 abbrevd9_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d9_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d9_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd9_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd9_0h0.o -I../common abbrevd9_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d9_0h0l1.o -I../common d9_0h0l1.f90
endif

d9_1h0l1: d9_1h0l1.f90 abbrevd9_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d9_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d9_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd9_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd9_1h0.o -I../common abbrevd9_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d9_1h0l1.o -I../common d9_1h0l1.f90
endif

d9_2h0l1: d9_2h0l1.f90 abbrevd9_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d9_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d9_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd9_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd9_2h0.o -I../common abbrevd9_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d9_2h0l1.o -I../common d9_2h0l1.f90
endif



d11_0h0l1: d11_0h0l1.f90 abbrevd11_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d11_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d11_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd11_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd11_0h0.o -I../common abbrevd11_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d11_0h0l1.o -I../common d11_0h0l1.f90
endif

d11_1h0l1: d11_1h0l1.f90 abbrevd11_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d11_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d11_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd11_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd11_1h0.o -I../common abbrevd11_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d11_1h0l1.o -I../common d11_1h0l1.f90
endif

d11_2h0l1: d11_2h0l1.f90 abbrevd11_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d11_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d11_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd11_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd11_2h0.o -I../common abbrevd11_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d11_2h0l1.o -I../common d11_2h0l1.f90
endif



d13_0h0l1: d13_0h0l1.f90 abbrevd13_0h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d13_0h0l1.txt
	$(MAKE) $(S) -f Makefile.source d13_0h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd13_0h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd13_0h0.o -I../common abbrevd13_0h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d13_0h0l1.o -I../common d13_0h0l1.f90
endif

d13_1h0l1: d13_1h0l1.f90 abbrevd13_1h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d13_1h0l1.txt
	$(MAKE) $(S) -f Makefile.source d13_1h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd13_1h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd13_1h0.o -I../common abbrevd13_1h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d13_1h0l1.o -I../common d13_1h0l1.f90
endif

d13_2h0l1: d13_2h0l1.f90 abbrevd13_2h0.f90 globals.o
ifeq ($(HAVE_ORIG_DIAGRAM_FILE),1)
	$(shell sed -e "s/Local diagram/Id diag/g" ../diagrams-1.hh > $(TEMPFILE))
	$(shell mv $(TEMPFILE) ../diagrams-1.hh)
endif
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(MAKE) $(S) -f Makefile.source d13_2h0l1.txt
	$(MAKE) $(S) -f Makefile.source d13_2h0l1.f90
	$(MAKE) $(S) -f Makefile.source abbrevd13_2h0.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o abbrevd13_2h0.o -I../common abbrevd13_2h0.f90
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o d13_2h0l1.o -I../common d13_2h0l1.f90
endif



$(OBJECTS_0): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<

$(OBJECTS_1): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<

$(OBJECTS_2): %.o: %.f90
	$(vecho) "-> Compiling $@ .."
	$(Q) $(FC) $(FC_OPTS) $(FCFLAGS) -c -o $@ -I../common $<



amplitude0_0.a: $(OBJECTS_0)
	$(Q) ar rs $@ $+
amplitude0_1.a: $(OBJECTS_1)
	$(Q) ar rs $@ $+
amplitude0_2.a: $(OBJECTS_2)
	$(Q) ar rs $@ $+


doc:

clean:
	$(Q)$(FIND) $(FIND_OPT) . \( -name '*.o' \
		-or -name '*.mod' -or -name '*.a' -or -name '*.so' \) \
		-exec rm \{} \;

very-clean: clean
	$(Q)rm -f filelist-source
ifeq ($(HAVE_MAKEFILE_SOURCE),1)
	$(Q)$(FIND) $(FIND_OPT) . \( \
		-name 'd*h0l[01].f90' \
		-or -name 'd*h0l[01]fr5.f90' \
		-or -name 'd*h0l[014]*.txt' \
		-or -name 'd*h0l1[123dmu]*.txt' \
		-or -name 'd*h0l1[123dmu]*.f90' \
		-or -name 'd*h0l[01]c.txt' \
		-or -name 'd*h0l[01]c.f90' \
		-or -name 'd*h0l[01]d.txt' \
		-or -name 'd*h0l[01]d.hh' \
		-or -name 'd*h0l[01].hh' \
		-or -name 'd*h0l1d.txt' \
		-or -name 'd*h0l1d.f90' \
		-or -name 'd*h0l[01]-fr.txt' \
		-or -name 'd*h0l[01].dat' \
		-or -name 'd*h0l[01].abb' \
		-or -name 'diagramsl0_0.f90' \
		-or -name 'abbrevd*h0.f90' \
		-or -name 'd*h0l[01].prc' \
		-or -name 'borndiag*.prc' \
		-or -name 'born*.txt' \
		-or -name 'born*.dat' \
		-or -name '*-stamp'  \
		-or -name 'lightconedecomp.prc' \
		\) -exec rm \{} \;
endif

filelist-source: source
	$(Q)$(FIND) $(FIND_OPT) . \( \
		-name '*.f90' \
		-or -name 'Makefile' \
		-or -name 'Makefile.dep' \
		\) -print > $@

include Makefile.dep
